import type { Dialogue } from "../types";

export const phase5Dialogues: Dialogue[] = [
  {
    id: "p5-dialogue-doctor",
    phaseId: 5,
    title: "At the Doctor's Office",
    context: "A visit to the doctor for stress-related symptoms.",
    lines: [
      {
        speaker: "Dr",
        speakerRole: "a",
        arabic: "أهلا، شو عم تحس؟",
        transliteration: "Ahla, shū ʕam tḥiss?",
        english: "Hello, what are you feeling?",
      },
      {
        speaker: "P",
        speakerRole: "b",
        arabic: "عندي وجع براسي من مبارح ومش قادر نام.",
        transliteration: "ʕindi wajaʕ b-rāsi min mbāriḥ w-mish ʔādir nām.",
        english: "I have a headache since yesterday and can't sleep.",
      },
      {
        speaker: "Dr",
        speakerRole: "a",
        arabic: "عندك حرارة؟ وشو عم تاكل؟",
        transliteration: "ʕindak ḥarāra? W-shū ʕam tākol?",
        english: "Do you have a fever? And what are you eating?",
      },
      {
        speaker: "P",
        speakerRole: "b",
        arabic: "ما عندي حرارة. بس مضغوط كتير بالشغل وما عم آكل منيح.",
        transliteration: "Mā ʕindi ḥarāra. Bas maḍghūṭ ktīr bish-shughl w-mā ʕam ākol mnīḥ.",
        english: "No fever. But very stressed at work and not eating well.",
      },
      {
        speaker: "Dr",
        speakerRole: "a",
        arabic: "هيدا الضغط عم يأثر عليك. لازم ترتاح وتاكل منتظم. رح أعطيك دوا خفيف.",
        transliteration: "Hēda ḍ-ḍaght ʕam yʔaththir ʕalēk. Lāzim trtāḥ w-tākol muntaẓam. Raḥ aʕṭīk dawa khafīf.",
        english: "This stress is affecting you. You need to rest and eat regularly. I'll give you a light medicine.",
      },
    ],
  },
  {
    id: "p5-dialogue-family-debate",
    phaseId: 5,
    title: "Family Debate — Should We Visit Lebanon?",
    context: "A couple discussing whether to visit Lebanon this summer.",
    lines: [
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "بدي نروح لبنان هالصيف. صار زمان ما شفنا الأهل.",
        transliteration: "Baddī nrūḥ Lubnān haṣ-ṣayf. Ṣār zamān mā shufna l-ahl.",
        english: "I want us to go to Lebanon this summer. It's been too long since we saw family.",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "فكرة حلوة بس الوضع هونيك مش مستقر. وبعدين التذاكر غالية كتير.",
        transliteration: "Fikra ḥilwe bas il-waḍ hūnīk mish mustaqirr. W-baʕdēn it-tazāker ghālye ktīr.",
        english: "Nice idea but the situation there isn't stable. Plus the tickets are very expensive.",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "والله صح. بس إذا ما رحنا هالسنة، رح نتمنى بعدين. الأهل مش شباب.",
        transliteration: "Wallah ṣaḥ. Bas iza mā ruḥna haṣ-sane, raḥ nitmanna baʕdēn. Il-ahl mish shabāb.",
        english: "That's true. But if we don't go this year, we'll regret it later. Family aren't young.",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "هيدا اللي عم يقلقني كمان. خلينا نشوف الأسعار ونحكي تاني.",
        transliteration: "Hēda illi ʕam yʔalqini kamān. Khalliīna nshūf il-asʕār w-nḥki tāni.",
        english: "That's what worries me too. Let's check prices and talk again.",
      },
    ],
  },
  {
    id: "p5-dialogue-political-discussion",
    phaseId: 5,
    title: "Political Discussion",
    context: "Two friends discussing current events and politics in Lebanon, expressing opinions politely.",
    lines: [
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "شفت الأخبار اليوم؟ الوضع عم يتأزم أكتر.",
        transliteration: "Shift il-akhbār il-yōm? Il-waḍʕ ʕam yitʔazzam aktar.",
        english: "Did you see the news today? The situation is getting worse.",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "إي والله. بس صراحة ما بعود فاجأني شي. كل يوم نفس القصة.",
        transliteration: "Ē wallah. Bas ṣarāḥa mā bʕūd fājaʔni shi. Kill yōm nafs il-ʔiṣṣa.",
        english: "Yes honestly. But frankly nothing surprises me anymore. Every day same story.",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "بس هالمرة في ناس عم تتحرك. الشباب ما عاد ساكتين.",
        transliteration: "Bas hal-marra fī nās ʕam titḥarrak. Ish-shabāb mā ʕād sāktīn.",
        english: "But this time people are moving. The youth aren't staying silent anymore.",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "معك حق. بس المشكلة إنو كل واحد عم يشد لجهة. ما في وحدة.",
        transliteration: "Maʕak ḥaʔʔ. Bas il-mushkle inno kill wāḥad ʕam yishidd la-jiha. Mā fī waḥde.",
        english: "You're right. But the problem is everyone is pulling in a different direction. There's no unity.",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "بعرف. بس أنا برأيي لازم نبلش من تحت. من البلديات والمجتمع المدني.",
        transliteration: "Baʕrif. Bas ana b-raʔyī lāzim nbalish min taḥt. Min il-baladiyyāt wil-mujtamaʕ il-madanī.",
        english: "I know. But in my opinion we need to start from the bottom. From municipalities and civil society.",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "يمكن معك حق. بس الناس يائسة. كل واحد بيفكر بالهجرة بدل ما يبقى ويغيّر.",
        transliteration: "Yimkin maʕak ḥaʔʔ. Bas in-nās yāʔise. Kill wāḥad byifakkir bil-hijra badāl mā yibʔa w-yighayyir.",
        english: "Maybe you're right. But people are hopeless. Everyone thinks about emigrating instead of staying and changing things.",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "بفهم عليك. بس اللي بيحب بلدو ما بيتركو. هيدا رأيي ومش ضروري كلنا نتفق.",
        transliteration: "Bafham ʕalēk. Bas illi byiḥibb baldō mā byitrkō. Hēda raʔyī w-mish ḍarūri killna nittifiq.",
        english: "I understand you. But those who love their country don't leave it. That's my opinion and we don't all have to agree.",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "الله يعين الكل. بالآخر كل واحد عندو ظروفو. المهم نحافظ على الأمل.",
        transliteration: "Allah yiʕīn il-kill. Bil-ākhir kill wāḥad ʕindō ẓurūfō. Il-muhimm nḥāfiẓ ʕal-amal.",
        english: "God help everyone. In the end everyone has their own circumstances. The important thing is to hold on to hope.",
      },
    ],
  },
  {
    id: "p5-dialogue-planning-trip-lebanon",
    phaseId: 5,
    title: "Planning a Trip to Lebanon",
    context: "A diaspora Lebanese person planning their summer trip back home with a friend who knows the country well.",
    lines: [
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "بدي أنظم رحلة عالبنان هالصيف. شو بتنصحني فيه؟ وين أروح؟",
        transliteration: "Baddī naẓẓim riḥle ʕa-Lubnān haṣ-ṣayf. Shū btinṣaḥni fī? Wēn arūḥ?",
        english: "I want to plan a trip to Lebanon this summer. What do you recommend? Where should I go?",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "لازم تروح على الأرز وبشري. الطبيعة هونيك مش معقولة. وإذا بتحب البحر، بيبلوس وجبيل لازم.",
        transliteration: "Lāzim trūḥ ʕal-Arz w-Bsharri. Iṭ-ṭabīʕa hūnīk mish maʕʔūle. W-iza btḥibb il-baḥr, Byblos w-Jbēl lāzim.",
        english: "You have to go to the Cedars and Bcharre. The nature there is unbelievable. And if you like the sea, Byblos and Jbeil are a must.",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "وقديش لازم ضل؟ أسبوعين كافية ولا بدي أكتر؟",
        transliteration: "W-ʔaddēsh lāzim ḍall? Usbūʕēn kāfye walla baddī aktar?",
        english: "And how long should I stay? Is two weeks enough or do I need more?",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "أسبوعين أقل شي. بس إذا بدك تشوف الجنوب وبعلبك كمان، حاول تلات أسابيع.",
        transliteration: "Usbūʕēn aʔall shi. Bas iza baddak tshūf ij-Janūb w-Baʕlabak kamān, ḥāwil tlāt asābīʕ.",
        english: "Two weeks minimum. But if you want to see the South and Baalbek too, try for three weeks.",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "وبالنسبة للأكل، وين أحسن محلات بيروت؟ بشتاق للمناقيش والتبولة.",
        transliteration: "W-bin-nisbe lal-akl, wēn aḥsan maḥallāt Bayrūt? Bishtāʔ lal-manāʔīsh wit-tabbūle.",
        english: "And regarding food, where are the best places in Beirut? I miss manousheh and tabbouleh.",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "روح على الفرن الشعبي الصبح كل يوم. والمساء روح على المطاعم بالحمرا ومار مخايل. بتناكل إصبعاتك!",
        transliteration: "Rūḥ ʕal-furn ish-shaʕbi iṣ-ṣubuḥ kill yōm. Wil-masa rūḥ ʕal-maṭāʕim bil-Ḥamra w-Mār Mkhāyil. Bitnākil iṣbaʕātak!",
        english: "Go to the local bakery every morning. And evenings go to restaurants in Hamra and Mar Mikhael. You'll eat your fingers off!",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "وشو لازم أعرف ثقافيا؟ في شي لازم أنتبهلو؟",
        transliteration: "W-shū lāzim aʕrif thaqāfiyyan? Fī shi lāzim intibihlo?",
        english: "And what should I know culturally? Is there anything I should be aware of?",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "أهم شي لا تقول لأ للأكل! إذا حدا عزمك على بيتو لازم تقبل. ولا تنسى تجيب هدية.",
        transliteration: "Ahamm shi lā tʔūl laʔ lal-akl! Iza ḥadan ʕazamak ʕala bēto lāzim tiʔbal. W-lā tinsa tjīb hadiyye.",
        english: "Most important: don't say no to food! If someone invites you to their home you must accept. And don't forget to bring a gift.",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "ههه صح! كمان سمعت إنو لازم أساوم بالأسواق القديمة. صح هيك؟",
        transliteration: "Hahaha ṣaḥ! Kamān smiʕt inno lāzim sāwim bil-aswāʔ il-ʔadīme. Ṣaḥ hēk?",
        english: "Haha right! I also heard you should bargain in the old markets. Is that true?",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "أكيد! ما تقبل أول سعر أبدا. وإذا حسيت غالي، إمشي وبيرجعو ينادوك!",
        transliteration: "Akīd! Mā tiʔbal awwal siʕr abadan. W-iza ḥassēt ghāli, imshī w-byirjʕū ynādūk!",
        english: "Absolutely! Never accept the first price. And if you feel it's expensive, walk away and they'll call you back!",
      },
    ],
  },
];
