import type { Dialogue } from "../types";

export const phase3Dialogues: Dialogue[] = [
  {
    id: "p3-dialogue-catching-up",
    phaseId: 3,
    title: "Catching Up After a Long Time",
    context: "Running into an old friend or relative after a long absence.",
    lines: [
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "مرحبا والله! مش شايفك من زمان، كيفك؟",
        transliteration: "Marḥaba wallah! Mish shāyfak min zamān, kīfak?",
        english: "Wow hello! Haven't seen you in ages, how are you?",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "منيح الحمد لله! صراحة مشغول كتير. شو أخبارك إنت؟",
        transliteration: "Mnīḥ il-ḥamdullah! Ṣarāḥa mashghūl ktīr. Shū akhbārak inta?",
        english: "Good, thank God! Honestly been really busy. Your news?",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "عم بدور على شغل جديد. يعني الوضع تعبان بس بتمنى يتحسن.",
        transliteration: "ʕam bdūr ʕala shughl jdīd. Yaʕni il-waḍ taʕbān bas btimanna yitḥassan.",
        english: "I'm looking for a new job. I mean, things are tough but hopefully improving.",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "إن شاء الله! أنت شاطر والله، رح تلاقي شي منيح. ما تقلق.",
        transliteration: "Inshallah! Inta shāṭer wallah, raḥ tlāʔi shi mnīḥ. Ma tʔlaʔ.",
        english: "God willing! You're capable, you'll find something good. Don't worry.",
      },
    ],
  },
  {
    id: "p3-dialogue-past",
    phaseId: 3,
    title: "Talking About the Past",
    context: "Reminiscing about childhood in Beirut with someone who shared those times.",
    lines: [
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "بتذكر لما كنا صغار ببيروت؟",
        transliteration: "Btizakkar lamma kinna zghar b-Bayrūt?",
        english: "Do you remember when we were young in Beirut?",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "آه والله! كنا نتلهى بالزواريب كل يوم. ذكريات حلوة كتير.",
        transliteration: "Āh wallah! Kinna ntlahha biz-zawārib kull yōm. Zikrayāt ḥilwe ktīr.",
        english: "Oh yes! We used to play in the alleys every day. Such sweet memories.",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "والأكل! كانت إمي بتعمل الكبة كل يوم جمعة.",
        transliteration: "Wil-akl! Kānit immī btaʕmal il-kibbe kull yōm jumaʕa.",
        english: "And the food! My mom would make kibbeh every Friday.",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "يا ريت نرجع لهيك وقت. الحياة كانت أبسط.",
        transliteration: "Yā rēt nirjaʕ la-hēk waʔt. Il-ḥayāt kānit absat.",
        english: "If only we could go back to those times. Life was simpler.",
      },
    ],
  },
  {
    id: "p3-dialogue-talking-family",
    phaseId: 3,
    title: "Talking About Family",
    context: "Describing family members, where they live, and what they do for a living.",
    lines: [
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "قديش في عندك إخوة؟",
        transliteration: "ʔAddēsh fī ʕindak ikhwe?",
        english: "How many siblings do you have?",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "عندي أخ وختين. أخي الكبير عايش بالسعودية وختي الزغيرة لسّا بالجامعة.",
        transliteration: "ʕIndī akh w-ikhtēn. Akhi il-kbīr ʕāyish bis-Saʕūdiyye w-ikhti iz-zghīre lissa bil-jāmʕa.",
        english: "I have a brother and two sisters. My older brother lives in Saudi and my younger sister is still at university.",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "وختك التانية شو بتعمل؟",
        transliteration: "W-ikhtik it-tānye shū btaʕmal?",
        english: "And your other sister, what does she do?",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "هيي معلمة بمدرسة ببيروت. متجوزة وعندها ولدين.",
        transliteration: "Hiyye mʕallme b-madrase b-Bayrūt. Mjawwaze w-ʕindha waladēn.",
        english: "She's a teacher at a school in Beirut. Married with two kids.",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "حلو! وأهلك وينن هلق؟ لسا بالضيعة؟",
        transliteration: "Ḥilu! W-ahlak wēnon hallaʔ? Lissa biḍ-ḍayʕa?",
        english: "Nice! And where are your parents now? Still in the village?",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "إي، بيي وإمي لسا بالضيعة. ما بيحبو المدينة. بيقولو كتير ضجة.",
        transliteration: "Ē, bayyi w-immi lissa biḍ-ḍayʕa. Mā byiḥibbu il-mdīne. Biʔūlo ktīr ḍajje.",
        english: "Yes, my dad and mom are still in the village. They don't like the city. They say it's too noisy.",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "معن حق! أنا كمان بشتاق للضيعة. الهوا والأكل الطازج...",
        transliteration: "Maʕon ḥaʔʔ! Ana kamān bishtāʔ laḍ-ḍayʕa. Il-hawa wil-akl iṭ-ṭāzij...",
        english: "They're right! I also miss the village. The air and the fresh food...",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "إي والله. كل ما بروح بقلن خذوني معكن! بس الشغل ببيروت.",
        transliteration: "Ē wallah. Kill mā brūḥ bʔillon khudūni maʕkon! Bas ish-shughl b-Bayrūt.",
        english: "Honestly yes. Every time I visit I tell them take me with you! But work is in Beirut.",
      },
    ],
  },
  {
    id: "p3-dialogue-childhood-memories",
    phaseId: 3,
    title: "Sharing Childhood Memories",
    context: "Two friends reminiscing about growing up, school, and their neighborhood.",
    lines: [
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "بتتذكر مدرستنا القديمة؟ مرقت من قدّامها مبارح.",
        transliteration: "Btitzzakkar madrастna il-ʔadīme? Mrʔet min ʔuddāmha mbāriḥ.",
        english: "Do you remember our old school? I passed by it yesterday.",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "كيف لأ! كنا نلعب بالساحة كل الفرصة. والأستاذ فادي كان يزعق علينا!",
        transliteration: "Kīf laʔ! Kinna nilʕab bis-sāḥa kull il-furṣa. Wil-ustāz Fādi kān yuzʕuʔ ʕalēna!",
        english: "Of course! We used to play in the yard every recess. And Mr. Fadi would yell at us!",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "هههه إي! وبتتذكر لما كنا نشتري سندويشة فلافل من أبو حسين بعد المدرسة؟",
        transliteration: "Hahaha ē! W-btitzzakkar lamma kinna nishtiri sandwīshet falāfil min Abu Ḥusēn baʕd il-madrase?",
        english: "Hahaha yes! And remember when we'd buy falafel sandwiches from Abu Hussein after school?",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "أطيب فلافل بالحارة كلها! كان يعطينا زيادة لأنو يعرف بيي.",
        transliteration: "Aṭyab falāfil bil-ḥāra kullha! Kān yaʕṭīna zyāde laʔanno yaʕrif bayyi.",
        english: "The best falafel in the whole neighborhood! He'd give us extra because he knew my dad.",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "وبالصيف كنا نروح عالبركة ونقعد لحد ما يعتم.",
        transliteration: "W-biṣ-ṣayf kinna nrūḥ ʕal-birke w-nuʔʕud la-ḥadd mā yiʕtim.",
        english: "And in summer we'd go to the pool and stay until it got dark.",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "وإمي كانت تعصب لأنو كنت أرجع عتمان. كانت تقلي وين كنت يا حيوان!",
        transliteration: "W-immi kānit tiʕṣab laʔanno kint irjaʕ ʕatmān. Kānit tiʔillī wēn kint ya ḥaywān!",
        english: "And my mom would get angry because I'd come back after dark. She'd say 'where were you, you animal!'",
      },
      {
        speaker: "A",
        speakerRole: "a",
        arabic: "هيك كانت الأمهات! بس هلق منشتاق لهالأيام.",
        transliteration: "Hēk kānit il-ummahāt! Bas hallaʔ mnishtāʔ la-hal-ayyām.",
        english: "That's how moms were! But now we miss those days.",
      },
      {
        speaker: "B",
        speakerRole: "b",
        arabic: "أيام ما كان في همّ. لا شغل، لا فواتير، لا مسؤولية. بس لعب وأكل.",
        transliteration: "Ayyām mā kān fī hamm. Lā shughl, lā fawātīr, lā masʔūliyye. Bas laʕb w-akl.",
        english: "Days with no worries. No work, no bills, no responsibility. Just playing and eating.",
      },
    ],
  },
];
