import type { VocabItem } from "../types";

export const phase1Vocab: VocabItem[] = [
  // ── Greetings & Daily Expressions ──
  {
    id: "p1-greetings-marhaba",
    phaseId: 1,
    arabic: "مرحبا",
    transliteration: "marḥaba",
    english: "Hello",
    category: "Greetings",
    partOfSpeech: "phrase",
    notes: "Universal Lebanese greeting",
  },
  {
    id: "p1-greetings-ahla-w-sahla",
    phaseId: 1,
    arabic: "أهلا وسهلا",
    transliteration: "ahla w sahla",
    english: "Welcome",
    category: "Greetings",
    partOfSpeech: "phrase",
    notes: "Warm welcome for guests",
  },
  {
    id: "p1-greetings-kifak",
    phaseId: 1,
    arabic: "كيفك؟",
    transliteration: "kīfak? / kīfik?",
    english: "How are you?",
    category: "Greetings",
    partOfSpeech: "phrase",
    notes: "m/f distinction",
  },
  {
    id: "p1-greetings-mnih",
    phaseId: 1,
    arabic: "منيح، شكراً",
    transliteration: "mnīḥ, shukran",
    english: "Good, thanks",
    category: "Greetings",
    partOfSpeech: "phrase",
    notes: "منيح = distinctly Lebanese",
  },
  {
    id: "p1-greetings-yislamu",
    phaseId: 1,
    arabic: "يسلمو",
    transliteration: "yislamu",
    english: "Bless your hands",
    category: "Greetings",
    partOfSpeech: "phrase",
    notes: "Said to thank for food or work",
  },
  {
    id: "p1-greetings-sahten",
    phaseId: 1,
    arabic: "صحتين",
    transliteration: "saḥtēn",
    english: "Cheers / Bon appétit",
    category: "Greetings",
    partOfSpeech: "phrase",
    notes: 'Lit. "two healths"',
  },
  {
    id: "p1-greetings-yaatik",
    phaseId: 1,
    arabic: "يعطيك العافية",
    transliteration: "yaʕṭīk il-ʕāfiye",
    english: "God give you health",
    category: "Greetings",
    partOfSpeech: "phrase",
    notes: "Said to someone working",
  },
  {
    id: "p1-greetings-maasalame",
    phaseId: 1,
    arabic: "مع السلامة",
    transliteration: "maʕ is-salāme",
    english: "Goodbye",
    category: "Greetings",
    partOfSpeech: "phrase",
    notes: '"Go with safety"',
  },
  {
    id: "p1-greetings-inshallah",
    phaseId: 1,
    arabic: "إن شاء الله",
    transliteration: "inshallah",
    english: "God willing",
    category: "Greetings",
    partOfSpeech: "phrase",
    notes: "Tone = everything",
  },
  {
    id: "p1-greetings-yalla",
    phaseId: 1,
    arabic: "يلا",
    transliteration: "yalla",
    english: "Let's go / come on",
    category: "Greetings",
    partOfSpeech: "phrase",
    notes: "Most versatile Lebanese word",
  },
  {
    id: "p1-greetings-khalas",
    phaseId: 1,
    arabic: "خلص",
    transliteration: "khalas",
    english: "Done / finished / enough",
    category: "Greetings",
    partOfSpeech: "phrase",
    notes: "Ubiquitous closer",
  },
  {
    id: "p1-greetings-wallah",
    phaseId: 1,
    arabic: "والله",
    transliteration: "wallah",
    english: "I swear / really",
    category: "Greetings",
    partOfSpeech: "phrase",
    notes: "Constant emphasis filler",
  },

  // ── Numbers ──
  {
    id: "p1-numbers-1",
    phaseId: 1,
    arabic: "واحد",
    transliteration: "wāḥad",
    english: "1",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-2",
    phaseId: 1,
    arabic: "تنين",
    transliteration: "tnēn",
    english: "2",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-3",
    phaseId: 1,
    arabic: "تلاتة",
    transliteration: "tlāte",
    english: "3",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-4",
    phaseId: 1,
    arabic: "أربعة",
    transliteration: "arbaʕa",
    english: "4",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-5",
    phaseId: 1,
    arabic: "خمسة",
    transliteration: "khamse",
    english: "5",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-6",
    phaseId: 1,
    arabic: "ستة",
    transliteration: "sitte",
    english: "6",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-7",
    phaseId: 1,
    arabic: "سبعة",
    transliteration: "sabʕa",
    english: "7",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-8",
    phaseId: 1,
    arabic: "تمانية",
    transliteration: "tmānye",
    english: "8",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-9",
    phaseId: 1,
    arabic: "تسعة",
    transliteration: "tisʕa",
    english: "9",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-10",
    phaseId: 1,
    arabic: "عشرة",
    transliteration: "ʕashara",
    english: "10",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-20",
    phaseId: 1,
    arabic: "عشرين",
    transliteration: "ʕishrīn",
    english: "20",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-100",
    phaseId: 1,
    arabic: "مية",
    transliteration: "mīye",
    english: "100",
    category: "Numbers",
    partOfSpeech: "number",
  },

  // ── Family ──
  {
    id: "p1-family-baba",
    phaseId: 1,
    arabic: "بابا",
    transliteration: "baba",
    english: "Dad",
    category: "Family",
    partOfSpeech: "noun",
  },
  {
    id: "p1-family-mama",
    phaseId: 1,
    arabic: "ماما",
    transliteration: "mama",
    english: "Mom",
    category: "Family",
    partOfSpeech: "noun",
  },
  {
    id: "p1-family-akh",
    phaseId: 1,
    arabic: "أخ",
    transliteration: "akh",
    english: "Brother",
    category: "Family",
    partOfSpeech: "noun",
  },
  {
    id: "p1-family-ukht",
    phaseId: 1,
    arabic: "أخت",
    transliteration: "ukht",
    english: "Sister",
    category: "Family",
    partOfSpeech: "noun",
  },
  {
    id: "p1-family-jidd",
    phaseId: 1,
    arabic: "جد",
    transliteration: "jidd",
    english: "Grandfather",
    category: "Family",
    partOfSpeech: "noun",
  },
  {
    id: "p1-family-teta",
    phaseId: 1,
    arabic: "تيتا",
    transliteration: "tēta",
    english: "Grandmother",
    category: "Family",
    partOfSpeech: "noun",
  },
  {
    id: "p1-family-amm",
    phaseId: 1,
    arabic: "عم",
    transliteration: "ʕamm",
    english: "Paternal uncle",
    category: "Family",
    partOfSpeech: "noun",
  },
  {
    id: "p1-family-khal",
    phaseId: 1,
    arabic: "خال",
    transliteration: "khāl",
    english: "Maternal uncle",
    category: "Family",
    partOfSpeech: "noun",
  },
  {
    id: "p1-family-ibn",
    phaseId: 1,
    arabic: "ابن",
    transliteration: "ibn",
    english: "Son",
    category: "Family",
    partOfSpeech: "noun",
  },
  {
    id: "p1-family-bint",
    phaseId: 1,
    arabic: "بنت",
    transliteration: "bint",
    english: "Daughter",
    category: "Family",
    partOfSpeech: "noun",
  },

  // ── Colors ──
  {
    id: "p1-colors-ahmar",
    phaseId: 1,
    arabic: "أحمر",
    transliteration: "aḥmar",
    english: "Red",
    category: "Colors",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "السيارة حمرا",
      transliteration: "is-sayyāra ḥamra",
      english: "The car is red",
    },
  },
  {
    id: "p1-colors-azra",
    phaseId: 1,
    arabic: "أزرق",
    transliteration: "azraʔ",
    english: "Blue",
    category: "Colors",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "السما زرقا",
      transliteration: "is-sama zarʔa",
      english: "The sky is blue",
    },
  },
  {
    id: "p1-colors-akhdar",
    phaseId: 1,
    arabic: "أخضر",
    transliteration: "akhḍar",
    english: "Green",
    category: "Colors",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "الشجرة خضرا",
      transliteration: "ish-shajara khaḍra",
      english: "The tree is green",
    },
  },
  {
    id: "p1-colors-asfar",
    phaseId: 1,
    arabic: "أصفر",
    transliteration: "aṣfar",
    english: "Yellow",
    category: "Colors",
    partOfSpeech: "adj",
  },
  {
    id: "p1-colors-abyad",
    phaseId: 1,
    arabic: "أبيض",
    transliteration: "abyaḍ",
    english: "White",
    category: "Colors",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "البيت أبيض",
      transliteration: "il-bēt abyaḍ",
      english: "The house is white",
    },
  },
  {
    id: "p1-colors-aswad",
    phaseId: 1,
    arabic: "أسود",
    transliteration: "aswad",
    english: "Black",
    category: "Colors",
    partOfSpeech: "adj",
  },
  {
    id: "p1-colors-burtuali",
    phaseId: 1,
    arabic: "برتقالي",
    transliteration: "burtuʔāli",
    english: "Orange",
    category: "Colors",
    partOfSpeech: "adj",
    notes: "From برتقال (orange fruit)",
  },
  {
    id: "p1-colors-bunni",
    phaseId: 1,
    arabic: "بني",
    transliteration: "bunni",
    english: "Brown",
    category: "Colors",
    partOfSpeech: "adj",
  },
  {
    id: "p1-colors-zahri",
    phaseId: 1,
    arabic: "زهري",
    transliteration: "zahri",
    english: "Pink",
    category: "Colors",
    partOfSpeech: "adj",
    notes: "From زهر (flowers)",
  },
  {
    id: "p1-colors-banafsaji",
    phaseId: 1,
    arabic: "بنفسجي",
    transliteration: "banafsaji",
    english: "Purple",
    category: "Colors",
    partOfSpeech: "adj",
    notes: "From بنفسج (violet flower)",
  },

  // ── Days of the Week ──
  {
    id: "p1-days-tnein",
    phaseId: 1,
    arabic: "التنين",
    transliteration: "it-tnēn",
    english: "Monday",
    category: "Days of the Week",
    partOfSpeech: "noun",
    notes: "Literally 'the two' (2nd day)",
    exampleSentence: {
      arabic: "بشوفك يوم التنين",
      transliteration: "bshūfak yōm it-tnēn",
      english: "I'll see you on Monday",
    },
  },
  {
    id: "p1-days-tleta",
    phaseId: 1,
    arabic: "التلاتا",
    transliteration: "it-tlēta",
    english: "Tuesday",
    category: "Days of the Week",
    partOfSpeech: "noun",
  },
  {
    id: "p1-days-arba",
    phaseId: 1,
    arabic: "الأربعا",
    transliteration: "il-arbaʕa",
    english: "Wednesday",
    category: "Days of the Week",
    partOfSpeech: "noun",
  },
  {
    id: "p1-days-khamis",
    phaseId: 1,
    arabic: "الخميس",
    transliteration: "il-khamīs",
    english: "Thursday",
    category: "Days of the Week",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "الخميس في عطلة",
      transliteration: "il-khamīs fi ʕuṭle",
      english: "Thursday is a holiday",
    },
  },
  {
    id: "p1-days-jomaa",
    phaseId: 1,
    arabic: "الجمعة",
    transliteration: "ij-jumʕa",
    english: "Friday",
    category: "Days of the Week",
    partOfSpeech: "noun",
  },
  {
    id: "p1-days-sabt",
    phaseId: 1,
    arabic: "السبت",
    transliteration: "is-sabt",
    english: "Saturday",
    category: "Days of the Week",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "السبت منروح عالسوق",
      transliteration: "is-sabt mnrūḥ ʕa-s-sūʔ",
      english: "On Saturday we go to the market",
    },
  },
  {
    id: "p1-days-ahad",
    phaseId: 1,
    arabic: "الأحد",
    transliteration: "il-aḥad",
    english: "Sunday",
    category: "Days of the Week",
    partOfSpeech: "noun",
  },

  // ── Body Parts ──
  {
    id: "p1-body-ras",
    phaseId: 1,
    arabic: "راس",
    transliteration: "rās",
    english: "Head",
    category: "Body Parts",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "راسي عم يوجعني",
      transliteration: "rāsi ʕam yūjaʕni",
      english: "My head is hurting me",
    },
  },
  {
    id: "p1-body-id",
    phaseId: 1,
    arabic: "إيد",
    transliteration: "īd",
    english: "Hand / arm",
    category: "Body Parts",
    partOfSpeech: "noun",
    notes: "Covers both hand and arm in Lebanese",
    exampleSentence: {
      arabic: "إغسل إيديك",
      transliteration: "ighsil īdēk",
      english: "Wash your hands",
    },
  },
  {
    id: "p1-body-ayn",
    phaseId: 1,
    arabic: "عين",
    transliteration: "ʕēn",
    english: "Eye",
    category: "Body Parts",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "عيونا حلوين",
      transliteration: "ʕyūna ḥilwīn",
      english: "Her eyes are beautiful",
    },
  },
  {
    id: "p1-body-timm",
    phaseId: 1,
    arabic: "تم",
    transliteration: "timm",
    english: "Mouth",
    category: "Body Parts",
    partOfSpeech: "noun",
    notes: "Lebanese-specific; MSA uses فم",
  },
  {
    id: "p1-body-nif",
    phaseId: 1,
    arabic: "نيف",
    transliteration: "nīf",
    english: "Nose",
    category: "Body Parts",
    partOfSpeech: "noun",
    notes: "Lebanese-specific; MSA uses أنف",
  },
  {
    id: "p1-body-izin",
    phaseId: 1,
    arabic: "أذن",
    transliteration: "izin",
    english: "Ear",
    category: "Body Parts",
    partOfSpeech: "noun",
  },
  {
    id: "p1-body-batin",
    phaseId: 1,
    arabic: "بطن",
    transliteration: "baṭin",
    english: "Stomach / belly",
    category: "Body Parts",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "بطني عم توجعني",
      transliteration: "baṭni ʕam tūjaʕni",
      english: "My stomach is hurting me",
    },
  },
  {
    id: "p1-body-dahir",
    phaseId: 1,
    arabic: "ضهر",
    transliteration: "ḍahir",
    english: "Back",
    category: "Body Parts",
    partOfSpeech: "noun",
    notes: "Lebanese pronunciation; MSA ظهر",
  },
  {
    id: "p1-body-ijir",
    phaseId: 1,
    arabic: "إجر",
    transliteration: "ijir",
    english: "Leg / foot",
    category: "Body Parts",
    partOfSpeech: "noun",
    notes: "Covers both leg and foot in Lebanese",
  },
  {
    id: "p1-body-alb",
    phaseId: 1,
    arabic: "قلب",
    transliteration: "ʔalb",
    english: "Heart",
    category: "Body Parts",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "من كل قلبي",
      transliteration: "min kill ʔalbi",
      english: "From all my heart",
    },
  },

  // ── Food & Drink ──
  {
    id: "p1-food-khubz",
    phaseId: 1,
    arabic: "خبز",
    transliteration: "khubz",
    english: "Bread",
    category: "Food & Drink",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "جيب خبز من الفرن",
      transliteration: "jīb khubz min il-firin",
      english: "Bring bread from the bakery",
    },
  },
  {
    id: "p1-food-may",
    phaseId: 1,
    arabic: "ماي",
    transliteration: "māy",
    english: "Water",
    category: "Food & Drink",
    partOfSpeech: "noun",
    notes: "Lebanese-specific; MSA uses ماء",
    exampleSentence: {
      arabic: "بدي كاسة ماي",
      transliteration: "baddi kāset māy",
      english: "I want a glass of water",
    },
  },
  {
    id: "p1-food-ahwe",
    phaseId: 1,
    arabic: "قهوة",
    transliteration: "ahwe",
    english: "Coffee",
    category: "Food & Drink",
    partOfSpeech: "noun",
    notes: "Lebanese coffee is a cultural institution",
    exampleSentence: {
      arabic: "بتحب تشرب قهوة؟",
      transliteration: "btḥibb tishrab ahwe?",
      english: "Do you want to drink coffee?",
    },
  },
  {
    id: "p1-food-lahme",
    phaseId: 1,
    arabic: "لحمة",
    transliteration: "laḥme",
    english: "Meat",
    category: "Food & Drink",
    partOfSpeech: "noun",
  },
  {
    id: "p1-food-djaj",
    phaseId: 1,
    arabic: "دجاج",
    transliteration: "djāj",
    english: "Chicken",
    category: "Food & Drink",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "اليوم طبخنا دجاج",
      transliteration: "il-yōm ṭbakhna djāj",
      english: "Today we cooked chicken",
    },
  },
  {
    id: "p1-food-rizz",
    phaseId: 1,
    arabic: "رز",
    transliteration: "rizz",
    english: "Rice",
    category: "Food & Drink",
    partOfSpeech: "noun",
  },
  {
    id: "p1-food-jibne",
    phaseId: 1,
    arabic: "جبنة",
    transliteration: "jibne",
    english: "Cheese",
    category: "Food & Drink",
    partOfSpeech: "noun",
  },
  {
    id: "p1-food-halib",
    phaseId: 1,
    arabic: "حليب",
    transliteration: "ḥalīb",
    english: "Milk",
    category: "Food & Drink",
    partOfSpeech: "noun",
  },
  {
    id: "p1-food-shay",
    phaseId: 1,
    arabic: "شاي",
    transliteration: "shāy",
    english: "Tea",
    category: "Food & Drink",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "بدي فنجان شاي",
      transliteration: "baddi finjān shāy",
      english: "I want a cup of tea",
    },
  },
  {
    id: "p1-food-fweke",
    phaseId: 1,
    arabic: "فواكه",
    transliteration: "fwāke",
    english: "Fruit",
    category: "Food & Drink",
    partOfSpeech: "noun",
  },
  {
    id: "p1-food-khudra",
    phaseId: 1,
    arabic: "خضرا",
    transliteration: "khuḍra",
    english: "Vegetables",
    category: "Food & Drink",
    partOfSpeech: "noun",
  },
  {
    id: "p1-food-hummus",
    phaseId: 1,
    arabic: "حمص",
    transliteration: "ḥummuṣ",
    english: "Hummus / chickpeas",
    category: "Food & Drink",
    partOfSpeech: "noun",
    notes: "Also refers to chickpeas; a Lebanese staple",
    exampleSentence: {
      arabic: "بحب الحمص كتير",
      transliteration: "bḥibb il-ḥummuṣ ktīr",
      english: "I love hummus a lot",
    },
  },

  // ── Around the House ──
  {
    id: "p1-house-beit",
    phaseId: 1,
    arabic: "بيت",
    transliteration: "bēt",
    english: "House / home",
    category: "Around the House",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "رح روح عالبيت",
      transliteration: "raḥ rūḥ ʕa-l-bēt",
      english: "I'm going home",
    },
  },
  {
    id: "p1-house-bab",
    phaseId: 1,
    arabic: "باب",
    transliteration: "bāb",
    english: "Door",
    category: "Around the House",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "سكّر الباب",
      transliteration: "sakkir il-bāb",
      english: "Close the door",
    },
  },
  {
    id: "p1-house-shubak",
    phaseId: 1,
    arabic: "شباك",
    transliteration: "shibbāk",
    english: "Window",
    category: "Around the House",
    partOfSpeech: "noun",
  },
  {
    id: "p1-house-tawle",
    phaseId: 1,
    arabic: "طاولة",
    transliteration: "ṭāwle",
    english: "Table",
    category: "Around the House",
    partOfSpeech: "noun",
  },
  {
    id: "p1-house-kursi",
    phaseId: 1,
    arabic: "كرسي",
    transliteration: "kursi",
    english: "Chair",
    category: "Around the House",
    partOfSpeech: "noun",
  },
  {
    id: "p1-house-matbakh",
    phaseId: 1,
    arabic: "مطبخ",
    transliteration: "maṭbakh",
    english: "Kitchen",
    category: "Around the House",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "ماما بالمطبخ",
      transliteration: "māma b-il-maṭbakh",
      english: "Mom is in the kitchen",
    },
  },
  {
    id: "p1-house-hammam",
    phaseId: 1,
    arabic: "حمام",
    transliteration: "ḥammām",
    english: "Bathroom",
    category: "Around the House",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "وين الحمام؟",
      transliteration: "wēn il-ḥammām?",
      english: "Where is the bathroom?",
    },
  },
  {
    id: "p1-house-takht",
    phaseId: 1,
    arabic: "تخت",
    transliteration: "takht",
    english: "Bed",
    category: "Around the House",
    partOfSpeech: "noun",
    notes: "Lebanese-specific; MSA uses سرير",
  },

  // ── Numbers 11–1000 ──
  {
    id: "p1-numbers-11",
    phaseId: 1,
    arabic: "حداعش",
    transliteration: "ḥdāʕash",
    english: "11",
    category: "Numbers",
    partOfSpeech: "number",
    notes: "Lebanese form; MSA إحدى عشر",
  },
  {
    id: "p1-numbers-12",
    phaseId: 1,
    arabic: "تناعش",
    transliteration: "tnāʕash",
    english: "12",
    category: "Numbers",
    partOfSpeech: "number",
    notes: "Lebanese form; MSA اثنا عشر",
  },
  {
    id: "p1-numbers-15",
    phaseId: 1,
    arabic: "خمستاعش",
    transliteration: "khamstaʕash",
    english: "15",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-30",
    phaseId: 1,
    arabic: "تلاتين",
    transliteration: "tlātīn",
    english: "30",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-50",
    phaseId: 1,
    arabic: "خمسين",
    transliteration: "khamsīn",
    english: "50",
    category: "Numbers",
    partOfSpeech: "number",
  },
  {
    id: "p1-numbers-1000",
    phaseId: 1,
    arabic: "ألف",
    transliteration: "alf",
    english: "1000",
    category: "Numbers",
    partOfSpeech: "number",
    exampleSentence: {
      arabic: "بدي ألف ليرة",
      transliteration: "baddi alf līra",
      english: "I want a thousand lira",
    },
  },
];
