import type { VocabItem } from "../types";

export const phase6Vocab: VocabItem[] = [
  // ── Advanced Expressions of the Lebanese Diaspora ──
  {
    id: "p6-expr-ya-ret",
    phaseId: 6,
    arabic: "يا ريت الزمن يرجع",
    transliteration: "yā rēt iz-zaman yirjaʕ",
    english: "If only time could return",
    category: "Diaspora Expressions",
    partOfSpeech: "expression",
    notes: "Profound Lebanese nostalgia. Used often by emigrants.",
  },
  {
    id: "p6-expr-ma-byitkassar",
    phaseId: 6,
    arabic: "لبناني ما بيتكسر",
    transliteration: "lubnāni mā byitkassar",
    english: "A Lebanese doesn't break",
    category: "Diaspora Expressions",
    partOfSpeech: "expression",
    notes: "Cultural resilience, said in hardship.",
  },
  {
    id: "p6-expr-byisir",
    phaseId: 6,
    arabic: "اللبناني بيصير بكل مكان",
    transliteration: "il-lubnāni byiṣīr b-kull makān",
    english: "The Lebanese thrives everywhere",
    category: "Diaspora Expressions",
    partOfSpeech: "expression",
    notes: "Pride in diaspora success.",
  },
  {
    id: "p6-expr-allah-yihmi",
    phaseId: 6,
    arabic: "الله يحمي لبنان",
    transliteration: "allah yiḥmi Lubnān",
    english: "God protect Lebanon",
    category: "Diaspora Expressions",
    partOfSpeech: "expression",
    notes: "Said with feeling, especially by those abroad.",
  },

  // ── Politics & Society ──
  {
    id: "p6-politics-hkume",
    phaseId: 6,
    arabic: "حكومة",
    transliteration: "ḥkūme",
    english: "Government",
    category: "Politics & Society",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "الحكومة ما عم تعمل شي",
      transliteration: "il-ḥkūme mā ʕam taʕmal shi",
      english: "The government isn't doing anything",
    },
  },
  {
    id: "p6-politics-rais",
    phaseId: 6,
    arabic: "رئيس",
    transliteration: "raʔīs",
    english: "President",
    category: "Politics & Society",
    partOfSpeech: "noun",
  },
  {
    id: "p6-politics-majlis",
    phaseId: 6,
    arabic: "مجلس النواب",
    transliteration: "majlis in-nuwwāb",
    english: "Parliament",
    category: "Politics & Society",
    partOfSpeech: "noun",
    notes: "Literally 'council of representatives'",
  },
  {
    id: "p6-politics-intikhabat",
    phaseId: 6,
    arabic: "انتخابات",
    transliteration: "intkhābāt",
    english: "Elections",
    category: "Politics & Society",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "الانتخابات الجاية مهمة",
      transliteration: "il-intkhābāt ij-jēye muhimme",
      english: "The upcoming elections are important",
    },
  },
  {
    id: "p6-politics-hizb",
    phaseId: 6,
    arabic: "حزب",
    transliteration: "ḥizb",
    english: "Political party",
    category: "Politics & Society",
    partOfSpeech: "noun",
  },
  {
    id: "p6-politics-muzahara",
    phaseId: 6,
    arabic: "مظاهرة",
    transliteration: "muẓāhara",
    english: "Demonstration / protest",
    category: "Politics & Society",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "في مظاهرة بوسط البلد",
      transliteration: "fi muẓāhara b-wasaṭ il-balad",
      english: "There's a demonstration downtown",
    },
  },
  {
    id: "p6-politics-hurriye",
    phaseId: 6,
    arabic: "حرية",
    transliteration: "ḥurriyye",
    english: "Freedom / liberty",
    category: "Politics & Society",
    partOfSpeech: "noun",
  },
  {
    id: "p6-politics-salam",
    phaseId: 6,
    arabic: "سلام",
    transliteration: "salām",
    english: "Peace",
    category: "Politics & Society",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "بدنا سلام",
      transliteration: "biddna salām",
      english: "We want peace",
    },
  },

  // ── Lebanese Cultural Terms ──
  {
    id: "p6-culture-dabke",
    phaseId: 6,
    arabic: "دبكة",
    transliteration: "dabke",
    english: "Dabke (traditional folk dance)",
    category: "Lebanese Cultural Terms",
    partOfSpeech: "noun",
    notes: "Line dance performed at weddings and celebrations",
    exampleSentence: {
      arabic: "يلا ندبك",
      transliteration: "yalla nidbik",
      english: "Let's dance dabke",
    },
  },
  {
    id: "p6-culture-ara",
    phaseId: 6,
    arabic: "عرق",
    transliteration: "ʕaraʔ",
    english: "Arak (anise-flavored spirit)",
    category: "Lebanese Cultural Terms",
    partOfSpeech: "noun",
    notes: "Lebanon's national alcoholic drink; served with water and ice",
  },
  {
    id: "p6-culture-tabbule",
    phaseId: 6,
    arabic: "تبولة",
    transliteration: "tabbūle",
    english: "Tabbouleh (parsley salad)",
    category: "Lebanese Cultural Terms",
    partOfSpeech: "noun",
    notes: "Iconic Lebanese dish; parsley-based, not bulgur-based",
  },
  {
    id: "p6-culture-kibbe",
    phaseId: 6,
    arabic: "كبة",
    transliteration: "kibbe",
    english: "Kibbeh (meat and bulgur dish)",
    category: "Lebanese Cultural Terms",
    partOfSpeech: "noun",
    notes: "Considered Lebanon's national dish",
    exampleSentence: {
      arabic: "إمي بتعمل أحسن كبة",
      transliteration: "immi btaʕmal aḥsan kibbe",
      english: "My mom makes the best kibbeh",
    },
  },
  {
    id: "p6-culture-zaatar",
    phaseId: 6,
    arabic: "زعتر",
    transliteration: "zaʕtar",
    english: "Za'atar (thyme herb mix)",
    category: "Lebanese Cultural Terms",
    partOfSpeech: "noun",
    notes: "Dried thyme mix with sumac and sesame; eaten with olive oil and bread",
  },
  {
    id: "p6-culture-manoushe",
    phaseId: 6,
    arabic: "منقوشة",
    transliteration: "manʔūshe",
    english: "Manoushe (flatbread with toppings)",
    category: "Lebanese Cultural Terms",
    partOfSpeech: "noun",
    notes: "Lebanon's quintessential breakfast; usually with za'atar or cheese",
    exampleSentence: {
      arabic: "بدي منقوشة زعتر",
      transliteration: "baddi manʔūshe zaʕtar",
      english: "I want a za'atar manoushe",
    },
  },
  {
    id: "p6-culture-knefe",
    phaseId: 6,
    arabic: "كنافة",
    transliteration: "knēfe",
    english: "Knafeh (cheese pastry dessert)",
    category: "Lebanese Cultural Terms",
    partOfSpeech: "noun",
    notes: "Sweet cheese pastry soaked in syrup; famous in Tripoli",
  },
  {
    id: "p6-culture-argileh",
    phaseId: 6,
    arabic: "أرجيلة",
    transliteration: "argīle",
    english: "Hookah / water pipe",
    category: "Lebanese Cultural Terms",
    partOfSpeech: "noun",
    notes: "Lebanese word; also called نرجيلة (nargīle) in other dialects",
    exampleSentence: {
      arabic: "بدك تشرب أرجيلة؟",
      transliteration: "baddak tishrab argīle?",
      english: "Do you want to smoke hookah?",
    },
  },
  {
    id: "p6-culture-balkon",
    phaseId: 6,
    arabic: "بلكون",
    transliteration: "balkōn",
    english: "Balcony",
    category: "Lebanese Cultural Terms",
    partOfSpeech: "noun",
    notes: "French loanword (balcon); central to Lebanese social life",
  },
  {
    id: "p6-culture-dayaa",
    phaseId: 6,
    arabic: "ضيعة",
    transliteration: "ḍayʕa",
    english: "Village",
    category: "Lebanese Cultural Terms",
    partOfSpeech: "noun",
    notes: "Every Lebanese family has a ضيعة (ancestral village)",
    exampleSentence: {
      arabic: "رحنا عالضيعة بالصيف",
      transliteration: "ruḥna ʕa-ḍ-ḍayʕa b-iṣ-ṣēf",
      english: "We went to the village in summer",
    },
  },

  // ── Advanced Expressions ──
  {
    id: "p6-adv-inshallah",
    phaseId: 6,
    arabic: "إن شاء الله",
    transliteration: "in shāʔ allāh",
    english: "God willing",
    category: "Advanced Expressions",
    partOfSpeech: "expression",
    notes: "Can mean genuine hope, polite maybe, or sarcastic never",
    exampleSentence: {
      arabic: "إن شاء الله منتلاقا بكرا",
      transliteration: "in shāʔ allāh mintalāʔa bukra",
      english: "God willing we'll meet tomorrow",
    },
  },
  {
    id: "p6-adv-yahmik",
    phaseId: 6,
    arabic: "يحميك الله",
    transliteration: "yaḥmīk allāh",
    english: "May God protect you",
    category: "Advanced Expressions",
    partOfSpeech: "expression",
    notes: "Said with deep affection, often by parents",
  },
  {
    id: "p6-adv-mish-shaghli",
    phaseId: 6,
    arabic: "مش شغلي",
    transliteration: "mish shughli",
    english: "Not my business",
    category: "Advanced Expressions",
    partOfSpeech: "expression",
    exampleSentence: {
      arabic: "مش شغلي شو بيعمل",
      transliteration: "mish shughli shū byaʕmal",
      english: "It's not my business what he does",
    },
  },
  {
    id: "p6-adv-mish-mistahil",
    phaseId: 6,
    arabic: "مش مستاهل",
    transliteration: "mish mistāhil",
    english: "It's not worth it",
    category: "Advanced Expressions",
    partOfSpeech: "expression",
    exampleSentence: {
      arabic: "مش مستاهل تزعل",
      transliteration: "mish mistāhil tizʕal",
      english: "It's not worth getting upset over",
    },
  },
  {
    id: "p6-adv-weinak-ghayib",
    phaseId: 6,
    arabic: "وينك غايب",
    transliteration: "wēnak ghāyib",
    english: "Long time no see / where have you been",
    category: "Advanced Expressions",
    partOfSpeech: "expression",
    notes: "Literally 'where are you, absent one'",
  },
  {
    id: "p6-adv-shu-fi-ma-fi",
    phaseId: 6,
    arabic: "شو في ما في",
    transliteration: "shū fi mā fi",
    english: "What's new? / What's going on?",
    category: "Advanced Expressions",
    partOfSpeech: "expression",
    notes: "Literally 'what is there, what isn't there'",
    exampleSentence: {
      arabic: "هلا، شو في ما في؟",
      transliteration: "hala, shū fi mā fi?",
      english: "Hey, what's new?",
    },
  },
  {
    id: "p6-adv-dabbir-halak",
    phaseId: 6,
    arabic: "دبّر حالك",
    transliteration: "dabbir ḥālak",
    english: "Figure it out / manage yourself",
    category: "Advanced Expressions",
    partOfSpeech: "expression",
    notes: "Can be encouraging or dismissive depending on tone",
  },
  {
    id: "p6-adv-khalli-balak",
    phaseId: 6,
    arabic: "خلّي بالك من حالك",
    transliteration: "khalli bālak min ḥālak",
    english: "Take care of yourself",
    category: "Advanced Expressions",
    partOfSpeech: "expression",
    notes: "Common farewell expression",
    exampleSentence: {
      arabic: "يلا مع السلامة، خلّي بالك من حالك",
      transliteration: "yalla maʕ is-salāme, khalli bālak min ḥālak",
      english: "Alright goodbye, take care of yourself",
    },
  },
  {
    id: "p6-adv-ishtaatillak",
    phaseId: 6,
    arabic: "اشتقتلك",
    transliteration: "ishta'tillak",
    english: "I miss you",
    category: "Advanced Expressions",
    partOfSpeech: "expression",
    notes: "Lebanese form; MSA اشتقت لك",
    exampleSentence: {
      arabic: "كتير اشتقتلك",
      transliteration: "ktīr ishta'tillak",
      english: "I miss you so much",
    },
  },
  {
    id: "p6-adv-mabruk",
    phaseId: 6,
    arabic: "مبروك",
    transliteration: "mabrūk",
    english: "Congratulations",
    category: "Advanced Expressions",
    partOfSpeech: "expression",
    notes: "Response is الله يبارك فيك (allāh ybārik fīk)",
    exampleSentence: {
      arabic: "مبروك العرس!",
      transliteration: "mabrūk il-ʕurs!",
      english: "Congratulations on the wedding!",
    },
  },
];
