import type { VocabItem } from "../types";

export const phase5Vocab: VocabItem[] = [
  // ── Everyday Lebanese Idioms ──
  {
    id: "p5-idiom-khod-balak",
    phaseId: 5,
    arabic: "خود بالك حالك",
    transliteration: "khōd bālak ḥālak",
    english: "Take care of yourself",
    category: "Idioms",
    partOfSpeech: "expression",
    notes: "Literal: Take your mind of yourself. Meaning: Stay safe / look after yourself",
  },
  {
    id: "p5-idiom-ktab-maftooh",
    phaseId: 5,
    arabic: "هو كتاب مفتوح",
    transliteration: "huwwe ktāb maftūḥ",
    english: "He's an open book",
    category: "Idioms",
    partOfSpeech: "expression",
    notes: "Totally transparent, no secrets",
  },
  {
    id: "p5-idiom-kafa",
    phaseId: 5,
    arabic: "كفى كفى",
    transliteration: "kafa kafa",
    english: "That's enough / I'm done",
    category: "Idioms",
    partOfSpeech: "expression",
    notes: "Stop it / I've had it",
  },
  {
    id: "p5-idiom-rabbna-karim",
    phaseId: 5,
    arabic: "ربنا كريم",
    transliteration: "rabbna karīm",
    english: "God willing it'll work out",
    category: "Idioms",
    partOfSpeech: "expression",
    notes: "Literal: Our Lord is generous. It'll be okay — trust in God",
  },
  {
    id: "p5-idiom-nawwarto",
    phaseId: 5,
    arabic: "نوّرتو البيت",
    transliteration: "nawwarto il-bēt",
    english: "You lit up the house",
    category: "Idioms",
    partOfSpeech: "expression",
    notes: "Welcome! Your presence brightens us",
  },
  {
    id: "p5-idiom-albo-dahab",
    phaseId: 5,
    arabic: "قلبو من دهب",
    transliteration: "ʔalbo min dahab",
    english: "Heart of gold",
    category: "Idioms",
    partOfSpeech: "expression",
    notes: "He's incredibly kind and generous",
  },
  {
    id: "p5-idiom-ma-sar-shi",
    phaseId: 5,
    arabic: "ما صار شي",
    transliteration: "mā ṣār shi",
    english: "Nothing happened",
    category: "Idioms",
    partOfSpeech: "expression",
    notes: "It's fine / no big deal / don't worry",
  },
  {
    id: "p5-idiom-ida-tawile",
    phaseId: 5,
    arabic: "إيدا طويلة",
    transliteration: "ēda ṭawīle",
    english: "She has a long hand",
    category: "Idioms",
    partOfSpeech: "expression",
    notes: "She's generous / very giving",
  },

  // ── Advanced Verbs ──
  {
    id: "p5-verbs-sharah",
    phaseId: 5,
    arabic: "شرح",
    transliteration: "sharaḥ",
    english: "To explain",
    category: "Advanced Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "فيك تشرحلي كمان مرة؟",
      transliteration: "fīk tishraḥli kamān marra?",
      english: "Can you explain to me again?",
    },
  },
  {
    id: "p5-verbs-aran",
    phaseId: 5,
    arabic: "قارن",
    transliteration: "ʔāran",
    english: "To compare",
    category: "Advanced Verbs",
    partOfSpeech: "verb",
  },
  {
    id: "p5-verbs-itna-ash",
    phaseId: 5,
    arabic: "اتناقش",
    transliteration: "itnāʔash",
    english: "To argue / discuss",
    category: "Advanced Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "ما بدي اتناقش معك",
      transliteration: "mā baddi itnāʔash maʕak",
      english: "I don't want to argue with you",
    },
  },
  {
    id: "p5-verbs-waad",
    phaseId: 5,
    arabic: "وعد",
    transliteration: "waʕad",
    english: "To promise",
    category: "Advanced Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "وعدتني ما تروح",
      transliteration: "waʕadtni mā trūḥ",
      english: "You promised me you wouldn't go",
    },
  },
  {
    id: "p5-verbs-algha",
    phaseId: 5,
    arabic: "ألغى",
    transliteration: "algha",
    english: "To cancel",
    category: "Advanced Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "ألغينا الاجتماع",
      transliteration: "alghēna il-ijtimāʕ",
      english: "We cancelled the meeting",
    },
  },
  {
    id: "p5-verbs-ajjal",
    phaseId: 5,
    arabic: "أجّل",
    transliteration: "ajjal",
    english: "To postpone",
    category: "Advanced Verbs",
    partOfSpeech: "verb",
  },
  {
    id: "p5-verbs-ishtaka",
    phaseId: 5,
    arabic: "اشتكى",
    transliteration: "ishtaka",
    english: "To complain",
    category: "Advanced Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "دايمًا عم يشتكي",
      transliteration: "dāyman ʕam yishtiki",
      english: "He's always complaining",
    },
  },
  {
    id: "p5-verbs-samah",
    phaseId: 5,
    arabic: "سامح",
    transliteration: "sāmaḥ",
    english: "To forgive",
    category: "Advanced Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "سامحني",
      transliteration: "sāmiḥni",
      english: "Forgive me",
    },
  },
  {
    id: "p5-verbs-zakkar",
    phaseId: 5,
    arabic: "ذكّر",
    transliteration: "zakkar",
    english: "To remind",
    category: "Advanced Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "ذكّرني بكرا",
      transliteration: "zakkirni bukra",
      english: "Remind me tomorrow",
    },
  },
  {
    id: "p5-verbs-tarjam",
    phaseId: 5,
    arabic: "ترجم",
    transliteration: "tarjam",
    english: "To translate",
    category: "Advanced Verbs",
    partOfSpeech: "verb",
  },

  // ── Lebanese Slang ──
  {
    id: "p5-slang-hilu",
    phaseId: 5,
    arabic: "حلو",
    transliteration: "ḥilu",
    english: "Cool / nice",
    category: "Lebanese Slang",
    partOfSpeech: "adj",
    notes: "Context-dependent: can mean beautiful, nice, cool, sweet",
    exampleSentence: {
      arabic: "هيدا حلو كتير",
      transliteration: "hayda ḥilu ktīr",
      english: "That's really cool",
    },
  },
  {
    id: "p5-slang-ya-zalame",
    phaseId: 5,
    arabic: "يا زلمة",
    transliteration: "ya zalame",
    english: "Dude / buddy / man",
    category: "Lebanese Slang",
    partOfSpeech: "expression",
    notes: "Very common male address; informal",
    exampleSentence: {
      arabic: "شو عم تعمل يا زلمة؟",
      transliteration: "shū ʕam taʕmal ya zalame?",
      english: "What are you doing, dude?",
    },
  },
  {
    id: "p5-slang-kazzab",
    phaseId: 5,
    arabic: "كذاب",
    transliteration: "kazzāb",
    english: "Liar",
    category: "Lebanese Slang",
    partOfSpeech: "adj",
  },
  {
    id: "p5-slang-majnun",
    phaseId: 5,
    arabic: "مجنون",
    transliteration: "majnūn",
    english: "Crazy",
    category: "Lebanese Slang",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "إنت مجنون؟",
      transliteration: "inta majnūn?",
      english: "Are you crazy?",
    },
  },
  {
    id: "p5-slang-azim",
    phaseId: 5,
    arabic: "عظيم",
    transliteration: "ʕaẓīm",
    english: "Awesome / great",
    category: "Lebanese Slang",
    partOfSpeech: "adj",
  },
  {
    id: "p5-slang-mhallak",
    phaseId: 5,
    arabic: "مهلّك",
    transliteration: "mhallak",
    english: "Exhausted / wasted",
    category: "Lebanese Slang",
    partOfSpeech: "adj",
    notes: "Lebanese-specific intensifier for tired",
    exampleSentence: {
      arabic: "مهلّك من الشغل",
      transliteration: "mhallak min ish-shughl",
      english: "Exhausted from work",
    },
  },
  {
    id: "p5-slang-madghut",
    phaseId: 5,
    arabic: "مضغوط",
    transliteration: "maḍghūṭ",
    english: "Stressed / under pressure",
    category: "Lebanese Slang",
    partOfSpeech: "adj",
  },
  {
    id: "p5-slang-mahzuz",
    phaseId: 5,
    arabic: "محظوظ",
    transliteration: "maḥẓūẓ",
    english: "Lucky",
    category: "Lebanese Slang",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "كتير محظوظ إنك هون",
      transliteration: "ktīr maḥẓūẓ innak hōn",
      english: "You're very lucky to be here",
    },
  },
  {
    id: "p5-slang-bakhil",
    phaseId: 5,
    arabic: "بخيل",
    transliteration: "bakhīl",
    english: "Stingy / cheap",
    category: "Lebanese Slang",
    partOfSpeech: "adj",
    notes: "Strong insult in Lebanese culture of generosity",
  },

  // ── Media & Entertainment ──
  {
    id: "p5-media-film",
    phaseId: 5,
    arabic: "فيلم",
    transliteration: "fīlm",
    english: "Movie / film",
    category: "Media & Entertainment",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "يلا نتفرج عفيلم",
      transliteration: "yalla nitfarraj ʕa-fīlm",
      english: "Let's watch a movie",
    },
  },
  {
    id: "p5-media-ughniye",
    phaseId: 5,
    arabic: "أغنية",
    transliteration: "ughniye",
    english: "Song",
    category: "Media & Entertainment",
    partOfSpeech: "noun",
  },
  {
    id: "p5-media-musalsal",
    phaseId: 5,
    arabic: "مسلسل",
    transliteration: "musalsal",
    english: "TV series / show",
    category: "Media & Entertainment",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "عم تابع مسلسل جديد",
      transliteration: "ʕam tābiʕ musalsal jdīd",
      english: "I'm following a new TV series",
    },
  },
  {
    id: "p5-media-akhbar",
    phaseId: 5,
    arabic: "أخبار",
    transliteration: "akhbār",
    english: "News",
    category: "Media & Entertainment",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "شو الأخبار اليوم؟",
      transliteration: "shū il-akhbār il-yōm?",
      english: "What's the news today?",
    },
  },
  {
    id: "p5-media-social",
    phaseId: 5,
    arabic: "سوشال ميديا",
    transliteration: "sōshal mīdya",
    english: "Social media",
    category: "Media & Entertainment",
    partOfSpeech: "noun",
    notes: "English loanword used widely",
  },
  {
    id: "p5-media-sura",
    phaseId: 5,
    arabic: "صورة",
    transliteration: "ṣūra",
    english: "Photo / picture",
    category: "Media & Entertainment",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "يلا ناخد صورة",
      transliteration: "yalla nēkhod ṣūra",
      english: "Let's take a photo",
    },
  },
  {
    id: "p5-media-video",
    phaseId: 5,
    arabic: "فيديو",
    transliteration: "fīdyo",
    english: "Video",
    category: "Media & Entertainment",
    partOfSpeech: "noun",
  },
  {
    id: "p5-media-anaat",
    phaseId: 5,
    arabic: "قناة",
    transliteration: "ʔanāt",
    english: "Channel",
    category: "Media & Entertainment",
    partOfSpeech: "noun",
  },

  // ── Religion & Holidays ──
  {
    id: "p5-religion-eid",
    phaseId: 5,
    arabic: "عيد",
    transliteration: "ʕīd",
    english: "Holiday / feast / Eid",
    category: "Religion & Holidays",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "كل عيد وإنت بخير",
      transliteration: "kill ʕīd w-inta b-khēr",
      english: "Happy holiday (to you)",
    },
  },
  {
    id: "p5-religion-ramadan",
    phaseId: 5,
    arabic: "رمضان",
    transliteration: "ramaḍān",
    english: "Ramadan",
    category: "Religion & Holidays",
    partOfSpeech: "noun",
    notes: "Holy month of fasting for Muslims",
  },
  {
    id: "p5-religion-milad",
    phaseId: 5,
    arabic: "عيد الميلاد",
    transliteration: "ʕīd il-mīlād",
    english: "Christmas",
    category: "Religion & Holidays",
    partOfSpeech: "noun",
    notes: "Literally 'feast of the birth'; widely celebrated in Lebanon",
  },
  {
    id: "p5-religion-knise",
    phaseId: 5,
    arabic: "كنيسة",
    transliteration: "knīse",
    english: "Church",
    category: "Religion & Holidays",
    partOfSpeech: "noun",
  },
  {
    id: "p5-religion-jeme",
    phaseId: 5,
    arabic: "جامع",
    transliteration: "jēmeʕ",
    english: "Mosque",
    category: "Religion & Holidays",
    partOfSpeech: "noun",
  },
  {
    id: "p5-religion-allah",
    phaseId: 5,
    arabic: "الله",
    transliteration: "allāh",
    english: "God",
    category: "Religion & Holidays",
    partOfSpeech: "noun",
    notes: "Used by both Muslims and Christians in Lebanon",
  },
  {
    id: "p5-religion-sala",
    phaseId: 5,
    arabic: "صلا",
    transliteration: "ṣala",
    english: "Prayer",
    category: "Religion & Holidays",
    partOfSpeech: "noun",
    notes: "Lebanese pronunciation; MSA صلاة",
  },
  {
    id: "p5-religion-barake",
    phaseId: 5,
    arabic: "بركة",
    transliteration: "barake",
    english: "Blessing",
    category: "Religion & Holidays",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "الله يباركلك",
      transliteration: "allāh ybāriklak",
      english: "God bless you",
    },
  },
];
