import type { VocabItem } from "../types";

export const phase4Vocab: VocabItem[] = [
  // ── Work & Technology ──
  {
    id: "p4-work-sharike",
    phaseId: 4,
    arabic: "شركة",
    transliteration: "sharike",
    english: "Company",
    category: "Work & Technology",
    partOfSpeech: "noun",
  },
  {
    id: "p4-work-mawzaf",
    phaseId: 4,
    arabic: "موظف",
    transliteration: "mawẓaf",
    english: "Employee",
    category: "Work & Technology",
    partOfSpeech: "noun",
  },
  {
    id: "p4-work-rais",
    phaseId: 4,
    arabic: "رئيس",
    transliteration: "raʔīs",
    english: "Boss / head",
    category: "Work & Technology",
    partOfSpeech: "noun",
  },
  {
    id: "p4-work-mashru",
    phaseId: 4,
    arabic: "مشروع",
    transliteration: "mashrūʕ",
    english: "Project",
    category: "Work & Technology",
    partOfSpeech: "noun",
  },
  {
    id: "p4-work-hasub",
    phaseId: 4,
    arabic: "حاسوب",
    transliteration: "ḥāsūb",
    english: "Computer",
    category: "Work & Technology",
    partOfSpeech: "noun",
  },
  {
    id: "p4-work-shabake",
    phaseId: 4,
    arabic: "شبكة",
    transliteration: "shabake",
    english: "Network",
    category: "Work & Technology",
    partOfSpeech: "noun",
  },
  {
    id: "p4-work-barnamij",
    phaseId: 4,
    arabic: "برنامج",
    transliteration: "barnāmij",
    english: "Program / software",
    category: "Work & Technology",
    partOfSpeech: "noun",
  },
  {
    id: "p4-work-bayanat",
    phaseId: 4,
    arabic: "بيانات",
    transliteration: "bayānāt",
    english: "Data",
    category: "Work & Technology",
    partOfSpeech: "noun",
  },
  {
    id: "p4-work-amn",
    phaseId: 4,
    arabic: "أمن",
    transliteration: "amn",
    english: "Security",
    category: "Work & Technology",
    partOfSpeech: "noun",
  },
  {
    id: "p4-work-hujum",
    phaseId: 4,
    arabic: "هجوم",
    transliteration: "hujūm",
    english: "Attack / assault",
    category: "Work & Technology",
    partOfSpeech: "noun",
  },

  // ── Health & Body ──
  {
    id: "p4-health-tabib",
    phaseId: 4,
    arabic: "طبيب",
    transliteration: "ṭabīb",
    english: "Doctor",
    category: "Health & Body",
    partOfSpeech: "noun",
  },
  {
    id: "p4-health-mustashfa",
    phaseId: 4,
    arabic: "مستشفى",
    transliteration: "mustasfā",
    english: "Hospital",
    category: "Health & Body",
    partOfSpeech: "noun",
  },
  {
    id: "p4-health-dawa",
    phaseId: 4,
    arabic: "دوا",
    transliteration: "dawa",
    english: "Medicine",
    category: "Health & Body",
    partOfSpeech: "noun",
  },
  {
    id: "p4-health-wajaa",
    phaseId: 4,
    arabic: "وجع",
    transliteration: "wajaʕ",
    english: "Pain / hurt (Lebanese)",
    category: "Health & Body",
    partOfSpeech: "noun",
  },
  {
    id: "p4-health-sihha",
    phaseId: 4,
    arabic: "صحة",
    transliteration: "ṣiḥḥa",
    english: "Health",
    category: "Health & Body",
    partOfSpeech: "noun",
  },
  {
    id: "p4-health-harara",
    phaseId: 4,
    arabic: "حرارة",
    transliteration: "ḥarāra",
    english: "Fever / temperature",
    category: "Health & Body",
    partOfSpeech: "noun",
  },
  {
    id: "p4-health-daght",
    phaseId: 4,
    arabic: "ضغط",
    transliteration: "ḍaght",
    english: "Blood pressure / stress",
    category: "Health & Body",
    partOfSpeech: "noun",
  },
  {
    id: "p4-health-kahl",
    phaseId: 4,
    arabic: "كحل عيون",
    transliteration: "kaḥl ʕyūn",
    english: "Eye problems (general)",
    category: "Health & Body",
    partOfSpeech: "noun",
  },

  // ── City Life & Places ──
  {
    id: "p4-city-zahme",
    phaseId: 4,
    arabic: "زحمة",
    transliteration: "zaḥme",
    english: "Traffic / crowds",
    category: "City Life & Places",
    partOfSpeech: "noun",
  },
  {
    id: "p4-city-hayy",
    phaseId: 4,
    arabic: "حي",
    transliteration: "ḥayy",
    english: "Neighborhood",
    category: "City Life & Places",
    partOfSpeech: "noun",
  },
  {
    id: "p4-city-tabi",
    phaseId: 4,
    arabic: "طابق",
    transliteration: "ṭābiq",
    english: "Floor / story (building)",
    category: "City Life & Places",
    partOfSpeech: "noun",
  },
  {
    id: "p4-city-mol",
    phaseId: 4,
    arabic: "مول",
    transliteration: "mōl",
    english: "Mall (from English)",
    category: "City Life & Places",
    partOfSpeech: "noun",
  },
  {
    id: "p4-city-bank",
    phaseId: 4,
    arabic: "بنك",
    transliteration: "bank",
    english: "Bank",
    category: "City Life & Places",
    partOfSpeech: "noun",
  },
  {
    id: "p4-city-dkane",
    phaseId: 4,
    arabic: "دكانة",
    transliteration: "dkāne",
    english: "Small shop / store",
    category: "City Life & Places",
    partOfSpeech: "noun",
  },
  {
    id: "p4-city-mataam",
    phaseId: 4,
    arabic: "مطعم",
    transliteration: "maṭʕam",
    english: "Restaurant",
    category: "City Life & Places",
    partOfSpeech: "noun",
  },
  {
    id: "p4-city-tari",
    phaseId: 4,
    arabic: "طريق",
    transliteration: "ṭarīʔ",
    english: "Road / path",
    category: "City Life & Places",
    partOfSpeech: "noun",
  },

  // ── Society & Abstract ──
  {
    id: "p4-society-mujtama",
    phaseId: 4,
    arabic: "مجتمع",
    transliteration: "mujtamaʕ",
    english: "Society / community",
    category: "Society & Abstract",
    partOfSpeech: "noun",
  },
  {
    id: "p4-society-hkume",
    phaseId: 4,
    arabic: "حكومة",
    transliteration: "ḥkūme",
    english: "Government",
    category: "Society & Abstract",
    partOfSpeech: "noun",
  },
  {
    id: "p4-society-azme",
    phaseId: 4,
    arabic: "أزمة",
    transliteration: "azme",
    english: "Crisis",
    category: "Society & Abstract",
    partOfSpeech: "noun",
  },
  {
    id: "p4-society-hurriye",
    phaseId: 4,
    arabic: "حرية",
    transliteration: "ḥurrīye",
    english: "Freedom",
    category: "Society & Abstract",
    partOfSpeech: "noun",
  },
  {
    id: "p4-society-tiqa",
    phaseId: 4,
    arabic: "ثقة",
    transliteration: "tiqa",
    english: "Trust / confidence",
    category: "Society & Abstract",
    partOfSpeech: "noun",
  },
  {
    id: "p4-society-ray",
    phaseId: 4,
    arabic: "رأي",
    transliteration: "raʔy",
    english: "Opinion",
    category: "Society & Abstract",
    partOfSpeech: "noun",
  },
  {
    id: "p4-society-taghyir",
    phaseId: 4,
    arabic: "تغيير",
    transliteration: "taghyīr",
    english: "Change",
    category: "Society & Abstract",
    partOfSpeech: "noun",
  },
  {
    id: "p4-society-masuliye",
    phaseId: 4,
    arabic: "مسؤولية",
    transliteration: "masʔūlīye",
    english: "Responsibility",
    category: "Society & Abstract",
    partOfSpeech: "noun",
  },

  // ── Body & Health (expanded) ──
  {
    id: "p4-health-waja-ras",
    phaseId: 4,
    arabic: "وجع راس",
    transliteration: "wajaʕ rās",
    english: "Headache",
    category: "Body & Health",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "عندي وجع راس فظيع",
      transliteration: "ʕindi wajaʕ rās faẓīʕ",
      english: "I have a terrible headache",
    },
  },
  {
    id: "p4-health-rashh",
    phaseId: 4,
    arabic: "رشح",
    transliteration: "rashiḥ",
    english: "Cold (illness)",
    category: "Body & Health",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "عندي رشح",
      transliteration: "ʕindi rashiḥ",
      english: "I have a cold",
    },
  },
  {
    id: "p4-health-waja-batin",
    phaseId: 4,
    arabic: "وجع بطن",
    transliteration: "wajaʕ baṭin",
    english: "Stomach ache",
    category: "Body & Health",
    partOfSpeech: "noun",
  },
  {
    id: "p4-health-diktir",
    phaseId: 4,
    arabic: "دكتور",
    transliteration: "daktūr",
    english: "Doctor",
    category: "Body & Health",
    partOfSpeech: "noun",
    notes: "More common colloquially than طبيب",
    exampleSentence: {
      arabic: "لازم تروح عالدكتور",
      transliteration: "lāzim trūḥ ʕa-d-daktūr",
      english: "You need to go to the doctor",
    },
  },
  {
    id: "p4-health-saydaliye",
    phaseId: 4,
    arabic: "صيدلية",
    transliteration: "ṣaydaliyye",
    english: "Pharmacy",
    category: "Body & Health",
    partOfSpeech: "noun",
  },
  {
    id: "p4-health-mawed",
    phaseId: 4,
    arabic: "موعد",
    transliteration: "mawʕid",
    english: "Appointment",
    category: "Body & Health",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "عندي موعد عند الدكتور",
      transliteration: "ʕindi mawʕid ʕind id-daktūr",
      english: "I have a doctor's appointment",
    },
  },
  {
    id: "p4-health-daman",
    phaseId: 4,
    arabic: "ضمان",
    transliteration: "ḍamān",
    english: "Insurance",
    category: "Body & Health",
    partOfSpeech: "noun",
    notes: "Also means guarantee",
  },

  // ── Work & Office ──
  {
    id: "p4-office-ijtimaa",
    phaseId: 4,
    arabic: "اجتماع",
    transliteration: "ijtimāʕ",
    english: "Meeting",
    category: "Work & Office",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "عندي اجتماع الساعة عشرة",
      transliteration: "ʕindi ijtimāʕ is-sēʕa ʕashara",
      english: "I have a meeting at ten",
    },
  },
  {
    id: "p4-office-email",
    phaseId: 4,
    arabic: "إيميل",
    transliteration: "īmēl",
    english: "Email",
    category: "Work & Office",
    partOfSpeech: "noun",
    notes: "English loanword",
  },
  {
    id: "p4-office-talifon",
    phaseId: 4,
    arabic: "تلفون",
    transliteration: "talifōn",
    english: "Phone",
    category: "Work & Office",
    partOfSpeech: "noun",
    notes: "French loanword (téléphone)",
  },
  {
    id: "p4-office-maktab",
    phaseId: 4,
    arabic: "مكتب",
    transliteration: "maktab",
    english: "Office / desk",
    category: "Work & Office",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "أنا بالمكتب",
      transliteration: "ana b-il-maktab",
      english: "I'm at the office",
    },
  },
  {
    id: "p4-office-maash",
    phaseId: 4,
    arabic: "معاش",
    transliteration: "maʕāsh",
    english: "Salary",
    category: "Work & Office",
    partOfSpeech: "noun",
  },
  {
    id: "p4-office-utle",
    phaseId: 4,
    arabic: "عطلة",
    transliteration: "ʕuṭle",
    english: "Vacation / holiday",
    category: "Work & Office",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "بدي عطلة",
      transliteration: "baddi ʕuṭle",
      english: "I need a vacation",
    },
  },
  {
    id: "p4-office-mawed-nihai",
    phaseId: 4,
    arabic: "موعد نهائي",
    transliteration: "mawʕid nihāʔi",
    english: "Deadline",
    category: "Work & Office",
    partOfSpeech: "noun",
  },
  {
    id: "p4-office-zamil",
    phaseId: 4,
    arabic: "زميل",
    transliteration: "zamīl",
    english: "Colleague",
    category: "Work & Office",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "زميلي بالشغل كتير منيح",
      transliteration: "zamīli b-ish-shughl ktīr mnīḥ",
      english: "My colleague at work is very nice",
    },
  },

  // ── Education ──
  {
    id: "p4-edu-madrase",
    phaseId: 4,
    arabic: "مدرسة",
    transliteration: "madrase",
    english: "School",
    category: "Education",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "الولاد بالمدرسة",
      transliteration: "il-wlād b-il-madrase",
      english: "The kids are at school",
    },
  },
  {
    id: "p4-edu-jemaa",
    phaseId: 4,
    arabic: "جامعة",
    transliteration: "jēmʕa",
    english: "University",
    category: "Education",
    partOfSpeech: "noun",
  },
  {
    id: "p4-edu-ustaz",
    phaseId: 4,
    arabic: "أستاذ",
    transliteration: "ustāz",
    english: "Teacher / professor",
    category: "Education",
    partOfSpeech: "noun",
    notes: "Also a respectful title for men",
  },
  {
    id: "p4-edu-taleb",
    phaseId: 4,
    arabic: "طالب",
    transliteration: "ṭāleb",
    english: "Student",
    category: "Education",
    partOfSpeech: "noun",
  },
  {
    id: "p4-edu-saff",
    phaseId: 4,
    arabic: "صف",
    transliteration: "ṣaff",
    english: "Class / classroom",
    category: "Education",
    partOfSpeech: "noun",
  },
  {
    id: "p4-edu-ktab",
    phaseId: 4,
    arabic: "كتاب",
    transliteration: "ktāb",
    english: "Book",
    category: "Education",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "عم بقرا كتاب جديد",
      transliteration: "ʕam biʔra ktāb jdīd",
      english: "I'm reading a new book",
    },
  },
  {
    id: "p4-edu-wajib",
    phaseId: 4,
    arabic: "واجب",
    transliteration: "wājib",
    english: "Homework / duty",
    category: "Education",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "عملت الواجب؟",
      transliteration: "ʕmilt il-wājib?",
      english: "Did you do the homework?",
    },
  },
  {
    id: "p4-edu-imtihan",
    phaseId: 4,
    arabic: "امتحان",
    transliteration: "imtiḥān",
    english: "Exam / test",
    category: "Education",
    partOfSpeech: "noun",
  },
  {
    id: "p4-edu-alame",
    phaseId: 4,
    arabic: "علامة",
    transliteration: "ʕalāme",
    english: "Grade / mark",
    category: "Education",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "أخدت علامة منيحة",
      transliteration: "akhadit ʕalāme mnīḥa",
      english: "I got a good grade",
    },
  },
  {
    id: "p4-edu-shahade",
    phaseId: 4,
    arabic: "شهادة",
    transliteration: "shahāde",
    english: "Degree / certificate",
    category: "Education",
    partOfSpeech: "noun",
  },

  // ── Emotions (expanded) ──
  {
    id: "p4-emotions-zaalan",
    phaseId: 4,
    arabic: "زعلان",
    transliteration: "zaʕlān",
    english: "Angry / upset",
    category: "Emotions Expanded",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "ليش زعلان؟",
      transliteration: "lēsh zaʕlān?",
      english: "Why are you upset?",
    },
  },
  {
    id: "p4-emotions-mfeja",
    phaseId: 4,
    arabic: "مفاجأ",
    transliteration: "mfājaʔ",
    english: "Surprised",
    category: "Emotions Expanded",
    partOfSpeech: "adj",
  },
  {
    id: "p4-emotions-mitwatter",
    phaseId: 4,
    arabic: "متوتر",
    transliteration: "mitwattir",
    english: "Nervous / tense",
    category: "Emotions Expanded",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "أنا متوتر من الامتحان",
      transliteration: "ana mitwattir min il-imtiḥān",
      english: "I'm nervous about the exam",
    },
  },
  {
    id: "p4-emotions-mithammes",
    phaseId: 4,
    arabic: "متحمس",
    transliteration: "mitḥammes",
    english: "Excited / enthusiastic",
    category: "Emotions Expanded",
    partOfSpeech: "adj",
  },
  {
    id: "p4-emotions-fakhur",
    phaseId: 4,
    arabic: "فخور",
    transliteration: "fakhūr",
    english: "Proud",
    category: "Emotions Expanded",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "أنا فخور فيك",
      transliteration: "ana fakhūr fīk",
      english: "I'm proud of you",
    },
  },
  {
    id: "p4-emotions-khajlan",
    phaseId: 4,
    arabic: "خجلان",
    transliteration: "khajlān",
    english: "Ashamed / embarrassed",
    category: "Emotions Expanded",
    partOfSpeech: "adj",
  },
  {
    id: "p4-emotions-gheran",
    phaseId: 4,
    arabic: "غيران",
    transliteration: "ghērān",
    english: "Jealous",
    category: "Emotions Expanded",
    partOfSpeech: "adj",
  },
  {
    id: "p4-emotions-mamnun",
    phaseId: 4,
    arabic: "ممنون",
    transliteration: "mamnūn",
    english: "Grateful / thankful",
    category: "Emotions Expanded",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "كتير ممنونلك",
      transliteration: "ktīr mamnūnlak",
      english: "I'm very grateful to you",
    },
  },
  {
    id: "p4-emotions-mallan",
    phaseId: 4,
    arabic: "ملّان",
    transliteration: "mallān",
    english: "Bored",
    category: "Emotions Expanded",
    partOfSpeech: "adj",
    notes: "Lebanese-specific form",
    exampleSentence: {
      arabic: "ملّان كتير",
      transliteration: "mallān ktīr",
      english: "I'm so bored",
    },
  },
  {
    id: "p4-emotions-mihtar",
    phaseId: 4,
    arabic: "محتار",
    transliteration: "miḥtār",
    english: "Confused / undecided",
    category: "Emotions Expanded",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "محتار شو أعمل",
      transliteration: "miḥtār shū aʕmal",
      english: "I'm confused about what to do",
    },
  },
];
