import type { VocabItem } from "../types";

export const phase3Vocab: VocabItem[] = [
  // ── Connectors ──
  {
    id: "p3-conn-bas",
    phaseId: 3,
    arabic: "بس",
    transliteration: "bas",
    english: "But / Only / Just",
    category: "Connectors",
    partOfSpeech: "expression",
    notes: "Most common contrast word",
  },
  {
    id: "p3-conn-wkaman",
    phaseId: 3,
    arabic: "وكمان",
    transliteration: "w-kamān",
    english: "And also",
    category: "Connectors",
    partOfSpeech: "expression",
    notes: "Adding information",
  },
  {
    id: "p3-conn-laanno",
    phaseId: 3,
    arabic: "لأنو",
    transliteration: "laʔanno",
    english: "Because",
    category: "Connectors",
    partOfSpeech: "expression",
    notes: "Giving reasons",
  },
  {
    id: "p3-conn-baaden",
    phaseId: 3,
    arabic: "بعدين",
    transliteration: "baʕdēn",
    english: "Then / After that",
    category: "Connectors",
    partOfSpeech: "expression",
    notes: "Sequencing events",
  },
  {
    id: "p3-conn-masalan",
    phaseId: 3,
    arabic: "متلًا",
    transliteration: "masalan",
    english: "For example",
    category: "Connectors",
    partOfSpeech: "expression",
    notes: "Giving examples",
  },
  {
    id: "p3-conn-yaani",
    phaseId: 3,
    arabic: "يعني",
    transliteration: "yaʕni",
    english: "I mean / like / so",
    category: "Connectors",
    partOfSpeech: "expression",
    notes: "Filler — use constantly",
  },
  {
    id: "p3-conn-saraha",
    phaseId: 3,
    arabic: "صراحة",
    transliteration: "ṣarāḥa",
    english: "Honestly / Frankly",
    category: "Connectors",
    partOfSpeech: "expression",
    notes: "Opening honest statement",
  },
  {
    id: "p3-conn-awwalshi",
    phaseId: 3,
    arabic: "أول شي",
    transliteration: "awwal shi",
    english: "First of all",
    category: "Connectors",
    partOfSpeech: "expression",
    notes: "Starting a list",
  },
  {
    id: "p3-conn-tayyeb",
    phaseId: 3,
    arabic: "طيب",
    transliteration: "ṭayyeb",
    english: "OK / Alright",
    category: "Connectors",
    partOfSpeech: "expression",
    notes: "Moving forward",
  },
  {
    id: "p3-conn-heda-hu",
    phaseId: 3,
    arabic: "هيدا هو",
    transliteration: "hēda hū",
    english: "That's it / Exactly",
    category: "Connectors",
    partOfSpeech: "expression",
    notes: "Confirming, agreeing",
  },

  // ── Topic Vocab: Family ──
  {
    id: "p3-topic-family-ahli",
    phaseId: 3,
    arabic: "أهلي عايشين بلبنان",
    transliteration: "ahli ʕāyshīn b-Lubnān",
    english: "My parents live in Lebanon",
    category: "Topics - Family",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-family-siblings",
    phaseId: 3,
    arabic: "عندي اثنين إخوة",
    transliteration: "ʕindi tnēn ikhwe",
    english: "I have two siblings",
    category: "Topics - Family",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-family-miss",
    phaseId: 3,
    arabic: "عم بوحشوني كتير",
    transliteration: "ʕam bwaḥshuní ktīr",
    english: "I miss them a lot",
    category: "Topics - Family",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-family-mother",
    phaseId: 3,
    arabic: "إمي حنونة كتير",
    transliteration: "immī ḥanūne ktīr",
    english: "My mother is very caring",
    category: "Topics - Family",
    partOfSpeech: "phrase",
  },

  // ── Topic Vocab: Childhood ──
  {
    id: "p3-topic-child-grewup",
    phaseId: 3,
    arabic: "كبرت بلبنان",
    transliteration: "kbirt b-Lubnān",
    english: "I grew up in Lebanon",
    category: "Topics - Childhood",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-child-moved",
    phaseId: 3,
    arabic: "انتقلت لأمريكا وعمري تمانية",
    transliteration: "intaʔalt la-Amrīka w-ʕumri tmāniye",
    english: "I moved to America when I was 8",
    category: "Topics - Childhood",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-child-play",
    phaseId: 3,
    arabic: "كنا نلعب بالشارع",
    transliteration: "kinna nlʕab bish-shāriʕ",
    english: "We used to play in the street",
    category: "Topics - Childhood",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-child-summers",
    phaseId: 3,
    arabic: "الصيف كان رهيب",
    transliteration: "iṣ-ṣayf kān rahīb",
    english: "The summers were amazing",
    category: "Topics - Childhood",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-child-remember",
    phaseId: 3,
    arabic: "ما نسيت شي",
    transliteration: "mā nsīt shi",
    english: "I haven't forgotten anything",
    category: "Topics - Childhood",
    partOfSpeech: "phrase",
  },

  // ── Topic Vocab: Work ──
  {
    id: "p3-topic-work-cyber",
    phaseId: 3,
    arabic: "بشتغل بمجال الأمن المعلوماتي",
    transliteration: "bishtghil b-majāl il-amn il-maʕlūmāti",
    english: "I work in cybersecurity",
    category: "Topics - Work",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-work-technical",
    phaseId: 3,
    arabic: "شغلي تقني",
    transliteration: "shughli taʔni",
    english: "My work is technical",
    category: "Topics - Work",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-work-searching",
    phaseId: 3,
    arabic: "هلق عم بدور على شغل",
    transliteration: "hallaʔ ʕam bdūr ʕala shughl",
    english: "I'm job searching right now",
    category: "Topics - Work",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-work-home",
    phaseId: 3,
    arabic: "بشتغل من البيت",
    transliteration: "bishtghil min il-bēt",
    english: "I work from home",
    category: "Topics - Work",
    partOfSpeech: "phrase",
  },

  // ── Topic Vocab: Food ──
  {
    id: "p3-topic-food-love",
    phaseId: 3,
    arabic: "بعشق الأكل اللبناني",
    transliteration: "baʕshaʔ il-akl il-lubnāni",
    english: "I love Lebanese food",
    category: "Topics - Food",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-food-kibbe",
    phaseId: 3,
    arabic: "إمي بتعمل أحسن كبة",
    transliteration: "immī btaʕmal aḥsan kibbe",
    english: "My mother makes the best kibbeh",
    category: "Topics - Food",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-food-bread",
    phaseId: 3,
    arabic: "ما في شي متل الخبز اللبناني",
    transliteration: "mā fi shi mitl il-khubz il-lubnāni",
    english: "Nothing compares to Lebanese bread",
    category: "Topics - Food",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-food-flavors",
    phaseId: 3,
    arabic: "عم بوحشني الطعم",
    transliteration: "ʕam bwaḥshnī iṭ-ṭaʕm",
    english: "I miss the flavors",
    category: "Topics - Food",
    partOfSpeech: "phrase",
  },

  // ── Topic Vocab: Life in America ──
  {
    id: "p3-topic-usa-different",
    phaseId: 3,
    arabic: "أمريكا مختلفة كتير عن لبنان",
    transliteration: "Amrīka mukhtalfe ktīr ʕan Lubnān",
    english: "America is very different from Lebanon",
    category: "Topics - Life in America",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-usa-home",
    phaseId: 3,
    arabic: "بس صار بيتي كمان",
    transliteration: "bas ṣār bēti kamān",
    english: "But it's become my home too",
    category: "Topics - Life in America",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-usa-cultures",
    phaseId: 3,
    arabic: "عندي التقافتين مع بعض",
    transliteration: "ʕindi it-taʔāftēn maʕ baʕḍ",
    english: "I carry both cultures",
    category: "Topics - Life in America",
    partOfSpeech: "phrase",
  },

  // ── Topic Vocab: Opinions ──
  {
    id: "p3-topic-opinion-bnazari",
    phaseId: 3,
    arabic: "بنظري…",
    transliteration: "b-naẓarī…",
    english: "In my opinion…",
    category: "Topics - Opinions",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-opinion-baatid",
    phaseId: 3,
    arabic: "بعتقد إنو…",
    transliteration: "baʕtiʔid inno…",
    english: "I think that…",
    category: "Topics - Opinions",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-opinion-agree",
    phaseId: 3,
    arabic: "موافق / مش موافق",
    transliteration: "wāfʔ / mish wāfʔ",
    english: "I agree / I disagree",
    category: "Topics - Opinions",
    partOfSpeech: "phrase",
  },
  {
    id: "p3-topic-opinion-honestly",
    phaseId: 3,
    arabic: "صراحة…",
    transliteration: "ṣarāḥa…",
    english: "Honestly…",
    category: "Topics - Opinions",
    partOfSpeech: "phrase",
  },

  // ── Emotions — Full Range (P3 vocab upgrade) ──
  {
    id: "p3-emotions-fakhur",
    phaseId: 3,
    arabic: "فخور",
    transliteration: "fakhūr",
    english: "Proud",
    category: "Emotions - Full Range",
    partOfSpeech: "adj",
  },
  {
    id: "p3-emotions-hani",
    phaseId: 3,
    arabic: "حانق",
    transliteration: "ḥāniʔ",
    english: "Angry / frustrated",
    category: "Emotions - Full Range",
    partOfSpeech: "adj",
  },
  {
    id: "p3-emotions-nadim",
    phaseId: 3,
    arabic: "نادم",
    transliteration: "nādim",
    english: "Regretful",
    category: "Emotions - Full Range",
    partOfSpeech: "adj",
  },
  {
    id: "p3-emotions-mushta",
    phaseId: 3,
    arabic: "مشتاق",
    transliteration: "mushtāʔ",
    english: "Longing / missing",
    category: "Emotions - Full Range",
    partOfSpeech: "adj",
  },
  {
    id: "p3-emotions-hayer",
    phaseId: 3,
    arabic: "حائر",
    transliteration: "ḥāyer",
    english: "Confused / lost",
    category: "Emotions - Full Range",
    partOfSpeech: "adj",
  },
  {
    id: "p3-emotions-alan",
    phaseId: 3,
    arabic: "قلقان",
    transliteration: "ʔalʔān",
    english: "Worried / anxious",
    category: "Emotions - Full Range",
    partOfSpeech: "adj",
  },
  {
    id: "p3-emotions-mamnun",
    phaseId: 3,
    arabic: "ممنون",
    transliteration: "mamnūn",
    english: "Grateful",
    category: "Emotions - Full Range",
    partOfSpeech: "adj",
  },
  {
    id: "p3-emotions-gheran",
    phaseId: 3,
    arabic: "غيران",
    transliteration: "ghērān",
    english: "Jealous",
    category: "Emotions - Full Range",
    partOfSpeech: "adj",
  },

  // ── Life & Abstract Words ──
  {
    id: "p3-abstract-watan",
    phaseId: 3,
    arabic: "وطن",
    transliteration: "waṭan",
    english: "Homeland",
    category: "Life & Abstract",
    partOfSpeech: "noun",
  },
  {
    id: "p3-abstract-ghurbe",
    phaseId: 3,
    arabic: "غربة",
    transliteration: "ghurbe",
    english: "Exile / living far from home",
    category: "Life & Abstract",
    partOfSpeech: "noun",
  },
  {
    id: "p3-abstract-zakra",
    phaseId: 3,
    arabic: "ذاكرة",
    transliteration: "zākra",
    english: "Memory",
    category: "Life & Abstract",
    partOfSpeech: "noun",
  },
  {
    id: "p3-abstract-helem",
    phaseId: 3,
    arabic: "حلم",
    transliteration: "ḥelem",
    english: "Dream",
    category: "Life & Abstract",
    partOfSpeech: "noun",
  },
  {
    id: "p3-abstract-najah",
    phaseId: 3,
    arabic: "نجاح",
    transliteration: "najāḥ",
    english: "Success",
    category: "Life & Abstract",
    partOfSpeech: "noun",
  },
  {
    id: "p3-abstract-mustabal",
    phaseId: 3,
    arabic: "مستقبل",
    transliteration: "mustaʔbal",
    english: "Future",
    category: "Life & Abstract",
    partOfSpeech: "noun",
  },
  {
    id: "p3-abstract-karim",
    phaseId: 3,
    arabic: "كريم",
    transliteration: "karīm",
    english: "Generous",
    category: "Life & Abstract",
    partOfSpeech: "adj",
  },
  {
    id: "p3-abstract-shater",
    phaseId: 3,
    arabic: "شاطر",
    transliteration: "shāṭer",
    english: "Smart / capable",
    category: "Life & Abstract",
    partOfSpeech: "adj",
  },

  // ── Weather & Nature ──
  {
    id: "p3-weather-shams",
    phaseId: 3,
    arabic: "شمس",
    transliteration: "shams",
    english: "Sun",
    category: "Weather & Nature",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "الشمس قوية اليوم",
      transliteration: "ish-shams ʔawiyye il-yōm",
      english: "The sun is strong today",
    },
  },
  {
    id: "p3-weather-shti",
    phaseId: 3,
    arabic: "شتي",
    transliteration: "shti",
    english: "Rain",
    category: "Weather & Nature",
    partOfSpeech: "noun",
    notes: "Lebanese-specific; MSA uses مطر",
    exampleSentence: {
      arabic: "عم تشتي برا",
      transliteration: "ʕam tishti barra",
      english: "It's raining outside",
    },
  },
  {
    id: "p3-weather-hawa",
    phaseId: 3,
    arabic: "هوا",
    transliteration: "hawa",
    english: "Wind / air",
    category: "Weather & Nature",
    partOfSpeech: "noun",
  },
  {
    id: "p3-weather-talj",
    phaseId: 3,
    arabic: "تلج",
    transliteration: "talj",
    english: "Snow",
    category: "Weather & Nature",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "في تلج بالجبل",
      transliteration: "fi talj b-ij-jabal",
      english: "There's snow on the mountain",
    },
  },
  {
    id: "p3-weather-harr",
    phaseId: 3,
    arabic: "حر",
    transliteration: "ḥarr",
    english: "Hot (weather)",
    category: "Weather & Nature",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "كتير حر اليوم",
      transliteration: "ktīr ḥarr il-yōm",
      english: "It's very hot today",
    },
  },
  {
    id: "p3-weather-bard",
    phaseId: 3,
    arabic: "برد",
    transliteration: "bard",
    english: "Cold (weather)",
    category: "Weather & Nature",
    partOfSpeech: "adj",
  },
  {
    id: "p3-weather-gheme",
    phaseId: 3,
    arabic: "غيمة",
    transliteration: "ghēme",
    english: "Cloud",
    category: "Weather & Nature",
    partOfSpeech: "noun",
  },
  {
    id: "p3-weather-sama",
    phaseId: 3,
    arabic: "سما",
    transliteration: "sama",
    english: "Sky",
    category: "Weather & Nature",
    partOfSpeech: "noun",
    notes: "Lebanese pronunciation; MSA سماء",
  },

  // ── Clothing ──
  {
    id: "p3-clothing-amis",
    phaseId: 3,
    arabic: "قميص",
    transliteration: "ʔamīṣ",
    english: "Shirt",
    category: "Clothing",
    partOfSpeech: "noun",
  },
  {
    id: "p3-clothing-bantalon",
    phaseId: 3,
    arabic: "بنطلون",
    transliteration: "banṭalōn",
    english: "Pants / trousers",
    category: "Clothing",
    partOfSpeech: "noun",
    notes: "French loanword (pantalon)",
  },
  {
    id: "p3-clothing-sarmaye",
    phaseId: 3,
    arabic: "صرماية",
    transliteration: "ṣarmāye",
    english: "Shoes",
    category: "Clothing",
    partOfSpeech: "noun",
    notes: "Lebanese-specific; also كندرة (kundara) in some regions",
    exampleSentence: {
      arabic: "وين صرمايتي؟",
      transliteration: "wēn ṣarmāyti?",
      english: "Where are my shoes?",
    },
  },
  {
    id: "p3-clothing-fustan",
    phaseId: 3,
    arabic: "فستان",
    transliteration: "fustān",
    english: "Dress",
    category: "Clothing",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "الفستان كتير حلو",
      transliteration: "il-fustān ktīr ḥilu",
      english: "The dress is very beautiful",
    },
  },
  {
    id: "p3-clothing-jakit",
    phaseId: 3,
    arabic: "جاكيت",
    transliteration: "jākit",
    english: "Jacket",
    category: "Clothing",
    partOfSpeech: "noun",
    notes: "English loanword",
  },
  {
    id: "p3-clothing-takiye",
    phaseId: 3,
    arabic: "طاقية",
    transliteration: "ṭāʔiyye",
    english: "Hat / beanie",
    category: "Clothing",
    partOfSpeech: "noun",
  },
  {
    id: "p3-clothing-shal",
    phaseId: 3,
    arabic: "شال",
    transliteration: "shāl",
    english: "Scarf / shawl",
    category: "Clothing",
    partOfSpeech: "noun",
  },
  {
    id: "p3-clothing-shanta",
    phaseId: 3,
    arabic: "شنطة",
    transliteration: "shanṭa",
    english: "Bag / purse",
    category: "Clothing",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "نسيت شنطتي بالسيارة",
      transliteration: "nsīt shanṭti b-is-sayyāra",
      english: "I forgot my bag in the car",
    },
  },

  // ── Shopping ──
  {
    id: "p3-shopping-masari",
    phaseId: 3,
    arabic: "مصاري",
    transliteration: "maṣāri",
    english: "Money",
    category: "Shopping",
    partOfSpeech: "noun",
    notes: "Lebanese-specific; MSA uses فلوس or نقود",
    exampleSentence: {
      arabic: "ما معي مصاري",
      transliteration: "mā maʕi maṣāri",
      english: "I don't have money on me",
    },
  },
  {
    id: "p3-shopping-ghali",
    phaseId: 3,
    arabic: "غالي",
    transliteration: "ghāli",
    english: "Expensive",
    category: "Shopping",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "هيدا غالي كتير",
      transliteration: "hayda ghāli ktīr",
      english: "This is very expensive",
    },
  },
  {
    id: "p3-shopping-rkhis",
    phaseId: 3,
    arabic: "رخيص",
    transliteration: "rkhīṣ",
    english: "Cheap",
    category: "Shopping",
    partOfSpeech: "adj",
  },
  {
    id: "p3-shopping-addesh",
    phaseId: 3,
    arabic: "قديش؟",
    transliteration: "ʔaddēsh?",
    english: "How much?",
    category: "Shopping",
    partOfSpeech: "expression",
    exampleSentence: {
      arabic: "قديش هيدا؟",
      transliteration: "ʔaddēsh hayda?",
      english: "How much is this?",
    },
  },
  {
    id: "p3-shopping-su",
    phaseId: 3,
    arabic: "سوق",
    transliteration: "sūʔ",
    english: "Market / souq",
    category: "Shopping",
    partOfSpeech: "noun",
  },
  {
    id: "p3-shopping-dkane",
    phaseId: 3,
    arabic: "دكانة",
    transliteration: "dkāne",
    english: "Shop / small store",
    category: "Shopping",
    partOfSpeech: "noun",
    notes: "The typical corner shop in Lebanon",
  },
  {
    id: "p3-shopping-dafaa",
    phaseId: 3,
    arabic: "دفع",
    transliteration: "dafaʕ",
    english: "To pay",
    category: "Shopping",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "أنا بدفع",
      transliteration: "ana bidfaʕ",
      english: "I'll pay",
    },
  },
  {
    id: "p3-shopping-wasl",
    phaseId: 3,
    arabic: "وصل",
    transliteration: "waṣl",
    english: "Receipt",
    category: "Shopping",
    partOfSpeech: "noun",
  },
  {
    id: "p3-shopping-sier",
    phaseId: 3,
    arabic: "سعر",
    transliteration: "siʕr",
    english: "Price",
    category: "Shopping",
    partOfSpeech: "noun",
  },
  {
    id: "p3-shopping-tanzilat",
    phaseId: 3,
    arabic: "تنزيلات",
    transliteration: "tanzīlāt",
    english: "Sales / discounts",
    category: "Shopping",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "في تنزيلات بالمول",
      transliteration: "fi tanzīlāt b-il-mōl",
      english: "There are sales at the mall",
    },
  },

  // ── Transportation ──
  {
    id: "p3-transport-sayyara",
    phaseId: 3,
    arabic: "سيارة",
    transliteration: "sayyāra",
    english: "Car",
    category: "Transportation",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "السيارة بالباركينغ",
      transliteration: "is-sayyāra b-il-bārkīng",
      english: "The car is in the parking lot",
    },
  },
  {
    id: "p3-transport-bass",
    phaseId: 3,
    arabic: "باص",
    transliteration: "bāṣ",
    english: "Bus",
    category: "Transportation",
    partOfSpeech: "noun",
    notes: "English loanword",
  },
  {
    id: "p3-transport-servis",
    phaseId: 3,
    arabic: "سرفيس",
    transliteration: "sērvīs",
    english: "Shared taxi / service taxi",
    category: "Transportation",
    partOfSpeech: "noun",
    notes: "French loanword; the main public transport in Lebanon",
  },
  {
    id: "p3-transport-tayyara",
    phaseId: 3,
    arabic: "طيارة",
    transliteration: "ṭayyāra",
    english: "Airplane",
    category: "Transportation",
    partOfSpeech: "noun",
  },
  {
    id: "p3-transport-tari",
    phaseId: 3,
    arabic: "طريق",
    transliteration: "ṭarīʔ",
    english: "Road / way",
    category: "Transportation",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "الطريق طويلة",
      transliteration: "iṭ-ṭarīʔ ṭawīle",
      english: "The road is long",
    },
  },
  {
    id: "p3-transport-zahme",
    phaseId: 3,
    arabic: "زحمة",
    transliteration: "zaḥme",
    english: "Traffic / congestion",
    category: "Transportation",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "في زحمة عالأوتوستراد",
      transliteration: "fi zaḥme ʕa-l-ōtōstrād",
      english: "There's traffic on the highway",
    },
  },
  {
    id: "p3-transport-barking",
    phaseId: 3,
    arabic: "باركينغ",
    transliteration: "bārkīng",
    english: "Parking",
    category: "Transportation",
    partOfSpeech: "noun",
    notes: "English loanword",
  },
  {
    id: "p3-transport-mahatta",
    phaseId: 3,
    arabic: "محطة بنزين",
    transliteration: "maḥaṭṭa benzīn",
    english: "Gas station",
    category: "Transportation",
    partOfSpeech: "noun",
    notes: "بنزين is a French loanword (benzine)",
  },

  // ── Expressing Opinions ──
  {
    id: "p3-opinion-baatid",
    phaseId: 3,
    arabic: "بعتقد",
    transliteration: "baʕtiʔid",
    english: "I think",
    category: "Expressing Opinions",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "بعتقد إنو صح",
      transliteration: "baʕtiʔid inno ṣaḥḥ",
      english: "I think it's correct",
    },
  },
  {
    id: "p3-opinion-brayi",
    phaseId: 3,
    arabic: "برأيي",
    transliteration: "b-raʔyi",
    english: "In my opinion",
    category: "Expressing Opinions",
    partOfSpeech: "expression",
  },
  {
    id: "p3-opinion-yimkin",
    phaseId: 3,
    arabic: "يمكن",
    transliteration: "yimkin",
    english: "Maybe / perhaps",
    category: "Expressing Opinions",
    partOfSpeech: "expression",
    exampleSentence: {
      arabic: "يمكن يجي بكرا",
      transliteration: "yimkin yīji bukra",
      english: "Maybe he'll come tomorrow",
    },
  },
  {
    id: "p3-opinion-akid",
    phaseId: 3,
    arabic: "أكيد",
    transliteration: "akīd",
    english: "Of course / definitely",
    category: "Expressing Opinions",
    partOfSpeech: "expression",
  },
  {
    id: "p3-opinion-maak-ha",
    phaseId: 3,
    arabic: "معك حق",
    transliteration: "maʕak ḥaʔʔ",
    english: "You're right / I agree",
    category: "Expressing Opinions",
    partOfSpeech: "expression",
    notes: "Literally 'you have the right'",
    exampleSentence: {
      arabic: "والله معك حق",
      transliteration: "wallah maʕak ḥaʔʔ",
      english: "Honestly, you're right",
    },
  },
  {
    id: "p3-opinion-mish-mwafe",
    phaseId: 3,
    arabic: "مش موافق",
    transliteration: "mish mwāfaʔ",
    english: "I disagree",
    category: "Expressing Opinions",
    partOfSpeech: "expression",
  },
];
