import type { VocabItem } from "../types";

export const phase2Vocab: VocabItem[] = [
  // ── Emotions ──
  {
    id: "p2-emotions-mabsut",
    phaseId: 2,
    arabic: "مبسوط",
    transliteration: "mabsūṭ",
    english: "Happy / pleased",
    category: "Emotions",
    partOfSpeech: "adj",
  },
  {
    id: "p2-emotions-taaban",
    phaseId: 2,
    arabic: "تعبان",
    transliteration: "taʕbān",
    english: "Tired / ill",
    category: "Emotions",
    partOfSpeech: "adj",
  },
  {
    id: "p2-emotions-madghut",
    phaseId: 2,
    arabic: "مضغوط",
    transliteration: "maḍghūṭ",
    english: "Stressed",
    category: "Emotions",
    partOfSpeech: "adj",
  },
  {
    id: "p2-emotions-zaalan",
    phaseId: 2,
    arabic: "زعلان",
    transliteration: "zaʕlān",
    english: "Upset / sad",
    category: "Emotions",
    partOfSpeech: "adj",
  },
  {
    id: "p2-emotions-murtah",
    phaseId: 2,
    arabic: "مرتاح",
    transliteration: "murtāḥ",
    english: "Relaxed",
    category: "Emotions",
    partOfSpeech: "adj",
  },
  {
    id: "p2-emotions-khayif",
    phaseId: 2,
    arabic: "خايف",
    transliteration: "khāyif",
    english: "Scared",
    category: "Emotions",
    partOfSpeech: "adj",
  },
  {
    id: "p2-emotions-mithammes",
    phaseId: 2,
    arabic: "متحمس",
    transliteration: "mitḥammes",
    english: "Excited",
    category: "Emotions",
    partOfSpeech: "adj",
  },
  {
    id: "p2-emotions-wahid",
    phaseId: 2,
    arabic: "وحيد",
    transliteration: "waḥīd",
    english: "Lonely",
    category: "Emotions",
    partOfSpeech: "adj",
  },

  // ── Time Words ──
  {
    id: "p2-time-halla",
    phaseId: 2,
    arabic: "هلق",
    transliteration: "hallaʔ",
    english: "Now",
    category: "Time Words",
    partOfSpeech: "expression",
  },
  {
    id: "p2-time-baaden",
    phaseId: 2,
    arabic: "بعدين",
    transliteration: "baʕdēn",
    english: "Later / then",
    category: "Time Words",
    partOfSpeech: "expression",
  },
  {
    id: "p2-time-mbarih",
    phaseId: 2,
    arabic: "مبارح",
    transliteration: "mbāriḥ",
    english: "Yesterday",
    category: "Time Words",
    partOfSpeech: "expression",
  },
  {
    id: "p2-time-bukra",
    phaseId: 2,
    arabic: "بكرا",
    transliteration: "bukra",
    english: "Tomorrow",
    category: "Time Words",
    partOfSpeech: "expression",
  },
  {
    id: "p2-time-dayman",
    phaseId: 2,
    arabic: "دايمًا",
    transliteration: "dāyman",
    english: "Always",
    category: "Time Words",
    partOfSpeech: "expression",
  },
  {
    id: "p2-time-abadan",
    phaseId: 2,
    arabic: "أبدًا",
    transliteration: "abadan",
    english: "Never",
    category: "Time Words",
    partOfSpeech: "expression",
  },
  {
    id: "p2-time-kaman",
    phaseId: 2,
    arabic: "كمان",
    transliteration: "kamān",
    english: "Also / again",
    category: "Time Words",
    partOfSpeech: "expression",
  },
  {
    id: "p2-time-badri",
    phaseId: 2,
    arabic: "بدري",
    transliteration: "badri",
    english: "Early",
    category: "Time Words",
    partOfSpeech: "expression",
  },

  // ── Common Verbs (present tense, 3rd person) ──
  {
    id: "p2-verbs-byihki",
    phaseId: 2,
    arabic: "بيحكي",
    transliteration: "byiḥki",
    english: "Speaks / talks",
    category: "Common Verbs",
    partOfSpeech: "verb",
  },
  {
    id: "p2-verbs-byaarif",
    phaseId: 2,
    arabic: "بيعرف",
    transliteration: "byaʕrif",
    english: "Knows",
    category: "Common Verbs",
    partOfSpeech: "verb",
  },
  {
    id: "p2-verbs-byihebb",
    phaseId: 2,
    arabic: "بيحب",
    transliteration: "byiḥebb",
    english: "Loves / likes",
    category: "Common Verbs",
    partOfSpeech: "verb",
  },
  {
    id: "p2-verbs-byirjaa",
    phaseId: 2,
    arabic: "بيرجع",
    transliteration: "byirjaʕ",
    english: "Returns",
    category: "Common Verbs",
    partOfSpeech: "verb",
  },
  {
    id: "p2-verbs-byishuf",
    phaseId: 2,
    arabic: "بيشوف",
    transliteration: "byishūf",
    english: "Sees / watches",
    category: "Common Verbs",
    partOfSpeech: "verb",
  },
  {
    id: "p2-verbs-byihtaj",
    phaseId: 2,
    arabic: "بيحتاج",
    transliteration: "byiḥtāj",
    english: "Needs",
    category: "Common Verbs",
    partOfSpeech: "verb",
  },
  {
    id: "p2-verbs-byifham",
    phaseId: 2,
    arabic: "بيفهم",
    transliteration: "byifham",
    english: "Understands",
    category: "Common Verbs",
    partOfSpeech: "verb",
  },
  {
    id: "p2-verbs-byiji",
    phaseId: 2,
    arabic: "بيجي",
    transliteration: "byīji",
    english: "Comes",
    category: "Common Verbs",
    partOfSpeech: "verb",
  },

  // ── Question Words ──
  {
    id: "p2-question-shu",
    phaseId: 2,
    arabic: "شو",
    transliteration: "shū",
    english: "What",
    category: "Question Words",
    partOfSpeech: "expression",
    notes: "شو بدك؟ — What do you want?",
  },
  {
    id: "p2-question-wen",
    phaseId: 2,
    arabic: "وين",
    transliteration: "wēn",
    english: "Where",
    category: "Question Words",
    partOfSpeech: "expression",
    notes: "وين رايح؟ — Where are you going?",
  },
  {
    id: "p2-question-emta",
    phaseId: 2,
    arabic: "إيمتى",
    transliteration: "ēmta",
    english: "When",
    category: "Question Words",
    partOfSpeech: "expression",
    notes: "إيمتى رح تجي؟ — When will you come?",
  },
  {
    id: "p2-question-min",
    phaseId: 2,
    arabic: "مين",
    transliteration: "mīn",
    english: "Who",
    category: "Question Words",
    partOfSpeech: "expression",
    notes: "مين هادا؟ — Who is this?",
  },
  {
    id: "p2-question-lesh",
    phaseId: 2,
    arabic: "ليش",
    transliteration: "lēsh",
    english: "Why",
    category: "Question Words",
    partOfSpeech: "expression",
    notes: "ليش ما جيت؟ — Why didn't you come?",
  },
  {
    id: "p2-question-addesh",
    phaseId: 2,
    arabic: "أديش",
    transliteration: "addēsh",
    english: "How much",
    category: "Question Words",
    partOfSpeech: "expression",
    notes: "أديش هادا؟ — How much is this?",
  },

  // ── Common Verbs (expanded) ──
  {
    id: "p2-verbs-akal",
    phaseId: 2,
    arabic: "أكل",
    transliteration: "akal",
    english: "To eat",
    category: "Common Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "أكلنا كتير مبارح",
      transliteration: "akalna ktīr mbāriḥ",
      english: "We ate a lot yesterday",
    },
  },
  {
    id: "p2-verbs-shirib",
    phaseId: 2,
    arabic: "شرب",
    transliteration: "shirib",
    english: "To drink",
    category: "Common Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "شربت قهوة الصبح",
      transliteration: "shribt ahwe iṣ-ṣubiḥ",
      english: "I drank coffee this morning",
    },
  },
  {
    id: "p2-verbs-nam",
    phaseId: 2,
    arabic: "نام",
    transliteration: "nām",
    english: "To sleep",
    category: "Common Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "ما نمت مبارح",
      transliteration: "mā nimt mbāriḥ",
      english: "I didn't sleep yesterday",
    },
  },
  {
    id: "p2-verbs-rah",
    phaseId: 2,
    arabic: "راح",
    transliteration: "rāḥ",
    english: "To go",
    category: "Common Verbs",
    partOfSpeech: "verb",
    notes: "Also used as future marker: رح (raḥ)",
    exampleSentence: {
      arabic: "رح روح عالسوق",
      transliteration: "raḥ rūḥ ʕa-s-sūʔ",
      english: "I'm going to go to the market",
    },
  },
  {
    id: "p2-verbs-ija",
    phaseId: 2,
    arabic: "إجا",
    transliteration: "ija",
    english: "To come",
    category: "Common Verbs",
    partOfSpeech: "verb",
    notes: "Irregular verb in Lebanese",
    exampleSentence: {
      arabic: "إجا عالبيت بكير",
      transliteration: "ija ʕa-l-bēt bakkīr",
      english: "He came home early",
    },
  },
  {
    id: "p2-verbs-shtaghal",
    phaseId: 2,
    arabic: "شغل",
    transliteration: "shtaghal",
    english: "To work",
    category: "Common Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "عم بشتغل من البيت",
      transliteration: "ʕam bishtghil min il-bēt",
      english: "I'm working from home",
    },
  },
  {
    id: "p2-verbs-shtara",
    phaseId: 2,
    arabic: "شرى",
    transliteration: "shtara",
    english: "To buy",
    category: "Common Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "شريت تلفون جديد",
      transliteration: "shtrēt talifōn jdīd",
      english: "I bought a new phone",
    },
  },
  {
    id: "p2-verbs-baa",
    phaseId: 2,
    arabic: "باع",
    transliteration: "bāʕ",
    english: "To sell",
    category: "Common Verbs",
    partOfSpeech: "verb",
  },
  {
    id: "p2-verbs-ata",
    phaseId: 2,
    arabic: "عطى",
    transliteration: "ʕaṭa",
    english: "To give",
    category: "Common Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "عطيني ياه",
      transliteration: "ʕaṭīni yā",
      english: "Give it to me",
    },
  },
  {
    id: "p2-verbs-akhad",
    phaseId: 2,
    arabic: "أخد",
    transliteration: "akhad",
    english: "To take",
    category: "Common Verbs",
    partOfSpeech: "verb",
    notes: "Lebanese-specific; MSA أخذ",
    exampleSentence: {
      arabic: "أخدت الكتاب",
      transliteration: "akhadit il-ktāb",
      english: "I took the book",
    },
  },
  {
    id: "p2-verbs-ara",
    phaseId: 2,
    arabic: "قرا",
    transliteration: "ʔara",
    english: "To read",
    category: "Common Verbs",
    partOfSpeech: "verb",
  },
  {
    id: "p2-verbs-katab",
    phaseId: 2,
    arabic: "كتب",
    transliteration: "katab",
    english: "To write",
    category: "Common Verbs",
    partOfSpeech: "verb",
  },
  {
    id: "p2-verbs-fatah",
    phaseId: 2,
    arabic: "فتح",
    transliteration: "fataḥ",
    english: "To open",
    category: "Common Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "فتح الباب",
      transliteration: "ftaḥ il-bāb",
      english: "Open the door",
    },
  },
  {
    id: "p2-verbs-sakkar",
    phaseId: 2,
    arabic: "سكّر",
    transliteration: "sakkar",
    english: "To close",
    category: "Common Verbs",
    partOfSpeech: "verb",
    notes: "Lebanese-specific; MSA uses أغلق",
    exampleSentence: {
      arabic: "سكّر الشباك",
      transliteration: "sakkir ish-shibbāk",
      english: "Close the window",
    },
  },
  {
    id: "p2-verbs-aad",
    phaseId: 2,
    arabic: "قعد",
    transliteration: "ʔaʕad",
    english: "To sit",
    category: "Common Verbs",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "تعال قعود هون",
      transliteration: "taʕāl ʔʕūd hōn",
      english: "Come sit here",
    },
  },

  // ── Daily Activities ──
  {
    id: "p2-daily-fa",
    phaseId: 2,
    arabic: "فاق",
    transliteration: "fāʔ",
    english: "To wake up",
    category: "Daily Activities",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "فقت بكير اليوم",
      transliteration: "fiʔit bakkīr il-yōm",
      english: "I woke up early today",
    },
  },
  {
    id: "p2-daily-ithammam",
    phaseId: 2,
    arabic: "اتحمم",
    transliteration: "itḥammam",
    english: "To shower",
    category: "Daily Activities",
    partOfSpeech: "verb",
  },
  {
    id: "p2-daily-tabakh",
    phaseId: 2,
    arabic: "طبخ",
    transliteration: "ṭabakh",
    english: "To cook",
    category: "Daily Activities",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "ماما عم تطبخ",
      transliteration: "māma ʕam tiṭbukh",
      english: "Mom is cooking",
    },
  },
  {
    id: "p2-daily-naddaf",
    phaseId: 2,
    arabic: "نضّف",
    transliteration: "naḍḍaf",
    english: "To clean",
    category: "Daily Activities",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "لازم ننضف البيت",
      transliteration: "lāzim nnaḍḍif il-bēt",
      english: "We have to clean the house",
    },
  },
  {
    id: "p2-daily-sa",
    phaseId: 2,
    arabic: "ساق",
    transliteration: "sāʔ",
    english: "To drive",
    category: "Daily Activities",
    partOfSpeech: "verb",
  },
  {
    id: "p2-daily-mishi",
    phaseId: 2,
    arabic: "مشي",
    transliteration: "mishi",
    english: "To walk",
    category: "Daily Activities",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "يلا نمشي شوي",
      transliteration: "yalla nimshi shway",
      english: "Let's walk a little",
    },
  },
  {
    id: "p2-daily-talfan",
    phaseId: 2,
    arabic: "تلفن",
    transliteration: "talfan",
    english: "To call (phone)",
    category: "Daily Activities",
    partOfSpeech: "verb",
    notes: "French loanword origin (téléphoner)",
    exampleSentence: {
      arabic: "تلفنلي بكرا",
      transliteration: "talfanli bukra",
      english: "Call me tomorrow",
    },
  },
  {
    id: "p2-daily-daras",
    phaseId: 2,
    arabic: "درس",
    transliteration: "daras",
    english: "To study",
    category: "Daily Activities",
    partOfSpeech: "verb",
  },
  {
    id: "p2-daily-salla",
    phaseId: 2,
    arabic: "صلّى",
    transliteration: "ṣalla",
    english: "To pray",
    category: "Daily Activities",
    partOfSpeech: "verb",
  },
  {
    id: "p2-daily-safar",
    phaseId: 2,
    arabic: "سافر",
    transliteration: "sāfar",
    english: "To travel",
    category: "Daily Activities",
    partOfSpeech: "verb",
    exampleSentence: {
      arabic: "سافرت عالبنان الصيف الماضي",
      transliteration: "sāfart ʕa-Lubnān iṣ-ṣēf il-māḍi",
      english: "I traveled to Lebanon last summer",
    },
  },

  // ── Adjectives ──
  {
    id: "p2-adj-kbir",
    phaseId: 2,
    arabic: "كبير",
    transliteration: "kbīr",
    english: "Big / old (age)",
    category: "Adjectives",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "البيت كبير",
      transliteration: "il-bēt kbīr",
      english: "The house is big",
    },
  },
  {
    id: "p2-adj-zghir",
    phaseId: 2,
    arabic: "صغير",
    transliteration: "zghīr",
    english: "Small / young",
    category: "Adjectives",
    partOfSpeech: "adj",
    notes: "Lebanese pronunciation zghīr (not ṣaghīr)",
  },
  {
    id: "p2-adj-skhin",
    phaseId: 2,
    arabic: "سخن",
    transliteration: "skhin",
    english: "Hot (temperature)",
    category: "Adjectives",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "الأكل سخن كتير",
      transliteration: "il-akl skhin ktīr",
      english: "The food is very hot",
    },
  },
  {
    id: "p2-adj-berid",
    phaseId: 2,
    arabic: "بارد",
    transliteration: "bārid",
    english: "Cold",
    category: "Adjectives",
    partOfSpeech: "adj",
  },
  {
    id: "p2-adj-jdid",
    phaseId: 2,
    arabic: "جديد",
    transliteration: "jdīd",
    english: "New",
    category: "Adjectives",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "عندي تلفون جديد",
      transliteration: "ʕindi talifōn jdīd",
      english: "I have a new phone",
    },
  },
  {
    id: "p2-adj-adim",
    phaseId: 2,
    arabic: "قديم",
    transliteration: "ʔadīm",
    english: "Old (things)",
    category: "Adjectives",
    partOfSpeech: "adj",
  },
  {
    id: "p2-adj-sari",
    phaseId: 2,
    arabic: "سريع",
    transliteration: "sarīʕ",
    english: "Fast",
    category: "Adjectives",
    partOfSpeech: "adj",
  },
  {
    id: "p2-adj-bati",
    phaseId: 2,
    arabic: "بطيء",
    transliteration: "baṭīʔ",
    english: "Slow",
    category: "Adjectives",
    partOfSpeech: "adj",
  },
  {
    id: "p2-adj-hilu",
    phaseId: 2,
    arabic: "حلو",
    transliteration: "ḥilu",
    english: "Beautiful / nice / sweet",
    category: "Adjectives",
    partOfSpeech: "adj",
    notes: "Very versatile: describes people, food, situations",
    exampleSentence: {
      arabic: "الطقس حلو اليوم",
      transliteration: "iṭ-ṭaʔs ḥilu il-yōm",
      english: "The weather is nice today",
    },
  },
  {
    id: "p2-adj-bshai",
    phaseId: 2,
    arabic: "بشع",
    transliteration: "bishʕ",
    english: "Ugly / awful",
    category: "Adjectives",
    partOfSpeech: "adj",
  },
  {
    id: "p2-adj-sahil",
    phaseId: 2,
    arabic: "سهل",
    transliteration: "sahil",
    english: "Easy",
    category: "Adjectives",
    partOfSpeech: "adj",
    exampleSentence: {
      arabic: "الامتحان كان سهل",
      transliteration: "il-imtiḥān kān sahil",
      english: "The exam was easy",
    },
  },
  {
    id: "p2-adj-saab",
    phaseId: 2,
    arabic: "صعب",
    transliteration: "ṣaʕb",
    english: "Hard / difficult",
    category: "Adjectives",
    partOfSpeech: "adj",
  },

  // ── Prepositions & Direction ──
  {
    id: "p2-prep-bi",
    phaseId: 2,
    arabic: "بـ / في",
    transliteration: "b- / fi",
    english: "In",
    category: "Prepositions & Direction",
    partOfSpeech: "expression",
    notes: "بـ is more common in Lebanese than في",
    exampleSentence: {
      arabic: "أنا بالبيت",
      transliteration: "ana b-il-bēt",
      english: "I'm at home",
    },
  },
  {
    id: "p2-prep-aa",
    phaseId: 2,
    arabic: "عـ",
    transliteration: "ʕa-",
    english: "On / to",
    category: "Prepositions & Direction",
    partOfSpeech: "expression",
    notes: "Short for على (ʕala)",
    exampleSentence: {
      arabic: "حط الكتاب عالطاولة",
      transliteration: "ḥuṭṭ il-ktāb ʕa-ṭ-ṭāwle",
      english: "Put the book on the table",
    },
  },
  {
    id: "p2-prep-taht",
    phaseId: 2,
    arabic: "تحت",
    transliteration: "taḥt",
    english: "Under / below",
    category: "Prepositions & Direction",
    partOfSpeech: "expression",
  },
  {
    id: "p2-prep-fo",
    phaseId: 2,
    arabic: "فوق",
    transliteration: "fōʔ",
    english: "Above / upstairs",
    category: "Prepositions & Direction",
    partOfSpeech: "expression",
    exampleSentence: {
      arabic: "هو فوق بالطابق التاني",
      transliteration: "huwwe fōʔ b-iṭ-ṭābiʔ it-tāni",
      english: "He's upstairs on the second floor",
    },
  },
  {
    id: "p2-prep-janb",
    phaseId: 2,
    arabic: "جنب",
    transliteration: "janb",
    english: "Next to / beside",
    category: "Prepositions & Direction",
    partOfSpeech: "expression",
  },
  {
    id: "p2-prep-ben",
    phaseId: 2,
    arabic: "بين",
    transliteration: "bēn",
    english: "Between",
    category: "Prepositions & Direction",
    partOfSpeech: "expression",
  },
  {
    id: "p2-prep-abl",
    phaseId: 2,
    arabic: "قبل",
    transliteration: "ʔabil",
    english: "Before",
    category: "Prepositions & Direction",
    partOfSpeech: "expression",
    exampleSentence: {
      arabic: "تعال قبل الساعة ستة",
      transliteration: "taʕāl ʔabil is-sēʕa sitte",
      english: "Come before 6 o'clock",
    },
  },
  {
    id: "p2-prep-baad",
    phaseId: 2,
    arabic: "بعد",
    transliteration: "baʕd",
    english: "After",
    category: "Prepositions & Direction",
    partOfSpeech: "expression",
  },
  {
    id: "p2-prep-yamin",
    phaseId: 2,
    arabic: "يمين",
    transliteration: "yamīn",
    english: "Right",
    category: "Prepositions & Direction",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "لف عاليمين",
      transliteration: "liff ʕa-l-yamīn",
      english: "Turn right",
    },
  },
  {
    id: "p2-prep-shmal",
    phaseId: 2,
    arabic: "شمال",
    transliteration: "shmāl",
    english: "Left",
    category: "Prepositions & Direction",
    partOfSpeech: "noun",
    exampleSentence: {
      arabic: "لف عالشمال",
      transliteration: "liff ʕa-sh-shmāl",
      english: "Turn left",
    },
  },
];
